### ISSUE TITLE
AutoFill does not see changes made in the main app (DB in iCloud)

### ISSUE THREAD

**Issue by Sunil-dev** [keepassium/KeePassium#10]
i used the old master key password and it worked still?

(would also be nice to have a feature that allows you to select multiple databases to either delete or export)

**Comment by keepassium** [comment]
> i used the old master key password and it worked still?

Mmm, I would need more details here... What did you do, what did you expect and what happened instead?

**Comment by Sunil-dev** [comment]
the databases don't sync (app and keychain) they accept different passwords and dont have the same passwords over i had to delete both and import separately

**Comment by keepassium** [comment]
Thanks for the clarification! Here's what I understood:

- You have added the same database to the main app and AutoFill
- Then you changed the master key of the database in the app
- Then you switched to AutoFill, and it rejected the new master key — but accepted the old one

Does that sound right?

If so, some additional details would be useful:

1) Where is your database stored (which cloud, or locally in the app?), and
2) Do you have the `Remember Master Keys` option enabled?
3) And since you mentioned deleting multiple databases... Can we rule out the possibility that AutoFill and the main app were given different DB files by accident?

**Comment by Sunil-dev** [comment]
that is correct 
1: icloud
2: yes 
3: the DB was the same i deleted all backups and never added more (so only one)

**Comment by keepassium** [comment]
@Sunil-dev, thanks for confirming. I tried a few times and could not reproduce the issue yet.

As a hypothesis, I imagine this can happen in some transient state, where AutoFill process lingers in background while you change the master key in the main app. Once you return to AutoFill, the system tells the AutoFill that the database file has changed, but for some reason it does not reload the file. 

I will need to read more about conflict resolution in iCloud to better understand what's going on here, and how to reproduce/fix this...

If anyone notices a similar issue, please chime in!

**Comment by keepassium** [comment]
Please check if the sync issue remains in beta 26. Thanks!

**Comment by Sunil-dev** [comment]
cant seem to replicate

**Comment by keepassium** [comment]
Awesome, thanks for confirming!
