### ISSUE TITLE
Opening database files with a different extensions (or no extension at all)

### ISSUE THREAD

**Issue by idiosyn** [keepassium/KeePassium#113]
**Describe a feature you'd like**

I want to open database files with different extensions or no extension at all.

**Additional context**

My database does not have the .kdbx extension. Because of that, I have to make a copy with the .kdbx extension and manually sync it.

**Comment by keepassium** [comment]
Thank you! I am surprised there is no earlier issue, because this is quite [a popular request](https://www.reddit.com/r/KeePassium/comments/goup5t/file_extension_requirement/).

To be done properly, this will need some preparatory work. (Instead of checking file extension, KeePassium should check file signature.) That work is part of a bigger upcoming refactoring that should enable several long-due features. Stay tuned!
