### ISSUE TITLE
Broken synchronization

### ISSUE THREAD

**Issue by jookovjook** [keepassium/KeePassium#124]
**Describe the bug**
Using iCloud, KeePassium sometimes ignores changes made to databases edited on other devices. And even **completely removes** some items!!!

**To Reproduce**
1. Open some db located in iCloud on **Device A**
2. Open the same db located in iCloud on **Device B**
3. Add an **Item B** to our db on **Device B**
4. Save the db, then the system automatically uploads saved db file from **Device B** into iCloud
5. Close the app on **Device B**
6. Add an **Item A** to our db on **Device A**
7. Save the database. Again, the system automatically uploads saved db file from **Device A** into iCloud
8. Open our db on **Device B**
9. **Item A** exists as expected on both devices, but **Item B** completely gone from both devices!

**Expected behavior**
When saving & opening databases KeePassium is expected to merge all the versions of databases edited from all the devices.

**User Information (please complete the following information):**
 - Device: iPhoneX
 - OS: iOS 14
 - App Version: v1.16.73

**Additional context**
Seems like the bug occurs when **Device A** uploads a db into iCloud before edits made by **Device B** being downloaded by **Device A** from iCloud. So, both devices almost simultaneously upload changes to iCloud, and then iCloud only saves the lastly uploaded file and uploads this file into all the devices.

**Comment by keepassium** [comment]
Thank you for the feedback. 

Entry-level sync is not broken — it's non-existent. At the moment, KeePassium sync works at the file level. That is, the app reads the latest database when opening; any changes are uploaded back online (as a file). 

This is not the final state: content-level sync is definitely planned. 

Until then, however, I would advice against opening the database on several devices simultaneously ("[Just avoid holding it in this way](https://arstechnica.com/gadgets/2010/06/jobs-on-iphone-4-antenna-avoid-holding-it-in-this-way/)").

**Comment by jookovjook** [comment]
@keepassium 
Thank you for you feedback!

Maybe it is possible to merge database from the latest backups, so the data will not be lost

**Comment by keepassium** [comment]
> Maybe it is possible to merge database from the latest backups, so the data will not be lost

In some cases, sure. But with two caveats:
- Timestamped backup files are made _before_ the changes. Their purpose is to protect the user from data loss if a bug in KeePassium saves an unusable database. Since they don't contain the latest local modification, they are useless for merging.
- The .latest backup files are automatically overwritten whenever you open a database (so any local changes saved in this file will be lost). So you would have to realize there are conflicting changes _before_ opening the database; then export the .latest backup file; then merge it with the remote database. (And merging has to be done in KeePass/KeePassXC for now.)

So, overall, it is much easier to refrain from opening the database on several devices :)

As for automatic merging, at the conceptual level it is fairly straightforward to do: when saving the local database, fetch the remote one, combine the changes, upload the result. But implementation-wise this is quite a massive task, so the progress is sadly slow.
