### ISSUE TITLE
Support for WatchOS

### ISSUE THREAD

**Issue by akissu** [keepassium/KeePassium#134]
I'd like to start off saying that this is the best keepass client I've used on the iOS platform, by far. Fingerprint support and Files app syncing pretty much has me locked into this app. However, it would also be nice to have Apple Watch support. Even just view only access to username, password, and notes would be great. Is something like this planned for the future? If not, would it be possible to fork the project and create a PoC myself?

**Comment by keepassium** [comment]
Thank you for the kind words, Alex! 

> Is something like this planned for the future? 

I don't plan Apple Watch support any time soon, for a whole set of reasons:

- There are quite a few things to improve in the iOS app (with macOS next in line), and I prefer to focus on one platform at a time.
- Over two years, there were exactly two requests for a companion watch app (this one included). So the potential audience is rather limited. 
- Being a diehard Pebble user, I don't know much about WatchOS capabilities, UI idioms and typical use cases. So I struggle to imagine scenarios where a watch app would be more convenient than pulling out the phone... 

> If not, would it be possible to fork the project and create a PoC myself?

Sure, it's GPL-licensed :) Do you plan to publish the PoC on the AppStore?

**Comment by keepassium** [comment]
Ok, I guess we're good here.

**Comment by rcarmo** [comment]
Hi! I’d like to be the third person requesting this, since I use TOTP on the watch (with 1Password) multiple times a day when I am using Windows machines and I haven’t my phone with me. In those cases I rely on the browser’s built in password managers for the first auth step but look up the TOTP code on the watch.

(Another use case is confirming card PIN numbers when at an ATM, but that one is less frequent  these days)

**Comment by keepassium** [comment]
Hi Rui, thanks for chiming in! I believe there are quite a few specialized TOTP apps for Apple Watch. And given that it's their main purpose, they would do a better job UX-wise (no need to display passwords, usernames, notes, etc)

**Comment by rcarmo** [comment]
Yes, but having to use two different apps raises other issues. 1Password does this very, very well, since it keeps what goes on to the watch to a minimum (I have TOTP and PINs for various things on mine).

Nobody expects a full blown app, but rather a SwiftUI view with a list of buttons.

**Comment by 0xC4N1** [comment]
I completely agree that focusing on one new platform at a time is a good practice and if there is not enough demand you should focus on other features. However I would like to raise another hand to increase the demand for a WatchOS companion app. Of course there are other TOTP apps but KeePassium support would be much appreciated since it significantly reduces the the amount of devices I need to set up and update TOTP tokens.

**Comment by ebits21** [comment]
I'll also chime in with a vote for being interested. I understand if it's not a priority.

I love KeePassium and would just want TOTP codes on the watch.
