### ISSUE TITLE
Local copy of keyfile

### ISSUE THREAD

**Issue by loeffelpan** [keepassium/KeePassium#142]
**Describe the bug**
Not sure if this is really a bug, but it‘s kind of confusing. Normal app context seems to create a copy if the keyfile in „KeePassium“ even when that keyfile is from local storage. Auto-Fill context does not create a copy and uses the keyfile from local storage as it is.
Is that the way it should work?

**To Reproduce**
1. Go to App
2. Unlock Database and add a keyfile from local storage.
3. Info shows that the location is „Local Storage -> KeePassium -> Local copy“ (see screeshot 1)
4. Same thing in Auto-Fill context leads to another result (see screenshot 2)
5. In files App there is a folder „KeePassium“ that is created for the local copy (and deleted when closing App?). The original keyfile is at root in local storage (see screeshot 3).

**Expected behavior**
This should give the same result in both cases.

**Screenshots**
![8FE422E6-E9FF-4EEE-8551-1B570EEDE503](https://user-images.githubusercontent.com/34661317/104959184-e7fbae00-59d1-11eb-880e-6d9fce2bd247.png)
![CA1A54BD-8169-41B7-85F8-6CABC612A594](https://user-images.githubusercontent.com/34661317/104959267-26916880-59d2-11eb-9445-d6456ee0d55e.png)
![62C3C900-ED92-47C9-8958-F1BD04460F2A](https://user-images.githubusercontent.com/34661317/104959277-2db87680-59d2-11eb-8bb8-073bce150c74.jpeg)

**User Information (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 14.2/14.3
 - App Version: 1.20.78

**Comment by keepassium** [comment]
> Normal app context seems to create a copy if the keyfile in „KeePassium“ even when that keyfile is from local storage. Auto-Fill context does not create a copy and uses the keyfile from local storage as it is.
> Is that the way it should work?

Yep, this is by design.

For the copy-creation, this is intended to reduce the database unlocking time. Few people want to wait extra 1-3-10 seconds to load a remote key file, especially if said file never changed in a decade. So making a local copy seems to make sense.

The different behavior between the app and its AutoFill extensions is more complicated... It was not a deliberate choice, it was the only solution I could find.

For the system, the main KeePassium app and its AutoFill extension are pretty much two separate apps. The main app has full access to its documents folder, which is also conveniently exposed as On My iPhone / KeePassium. The app can do anything with these files: read/write without any additional permission, get their paths, change their attributes, and so on.

The AutoFill extension, however, is treated as a separate app — so it does not have any privileges to access that folder. The only way it can access files in the app's document folder is via special references. This is the same approach KeePassium uses for cloud-based files. It requires that the user specifically selects the target file (thus implicitly granting the permission to access the file). And file references don't include information about file path — so AutoFill cannot distinguish between files in On My iPhone, or in some of its subfolders.

The special file references I mentioned before are also process-specific. If the main app tries to share a file reference with the AutoFill extension, this won't work. The system will just tell the AutoFill that the latter does not have permission to access that reference. Because the reference grants access rights only to the app itself, not the AutoFill. 

In the early days, I've spent a week of focused research to find a better solution. Eventually, however, I had to settle with two separate/independent file lists. The main app has its list of file references (and access permissions), and the AutoFill has its own, completely independent list (and associated permissions). When you add or remove a file to the main app, the AutoFill does not know anything about it; and vice versa. This is a major source of user confusion, unfortunately... 

---

As for your specific setup, you have two copies of the key file now, one in _On My iPhone_ and another one in _On My iPhone / KeePassium_. I would suggest to point the AutoFill to use _On My iPhone/KeePassium/KeePass.key_. This way, both the app and the AutoFill will use the same file, and you will be able to delete the one in _On My iPhone_. (But this won't change the File Location info in the AutoFill anyway, due to the reasons above.)
