### ISSUE TITLE
Synchronization Issue with Synology Drive on IOS

### ISSUE THREAD

**Issue by BeggaOnGitHub** [keepassium/KeePassium#149]
The connected Database on KeePassium via. Drive will not be Updated If a newer Version is available on the Driveserver.

When I open the KeePassium App and start the refresh of the Database I can see a loading bar, but after the refresh is done, compared to the server, there is still an older Version of the Database. To check If the Issue is on the Drive App, I opened it, but there I can see the newest Version. Even when I first open the Drive App, for updating the Database and after that I open the KeePassium App, there is still the same Issue.

-The only workaround that helps, is to open the Files App (from IOS) and navigate to the folder where the Database is. Then I can go to KeePassium and after a refresh of the Database, there is the newest version.
-Also a new connection to the Database is working.

Environment
 - IOS: 14.4
 - App Version: 1.21.81

**Comment by keepassium** [comment]
This is a [known issue](https://keepassium.com/articles/sync-ios-keepass-with-synology-nas/) in Synology Drive: it provides KeePassium a cached copy of the database, and completely forgets about that file. I have reported this to Synology support in August 2020 (ticket 2604475). Their response ended with:

> Upon further inspection, our developer confirmed that on some occasions, when using the iOS Files app to browse files on Drive, it does not show the latest version of the files. 
> They are currently working on a fix that will be released on a later date.

You can ping Synology to ask if "later date" is any time soon. Since the issue happens outside of KeePassium, I cannot do much about it... 

In the meanwhile, the best solution is to [enable WebDAV](https://www.synology.com/en-global/knowledgebase/DSM/help/WebDAVServer/webdav_server) on your NAS and [sync KeePassium using WebDAV](https://keepassium.com/articles/sync-ios-keepass-with-webdav/).
