### ISSUE TITLE
Lifetime Premium not found in Mac Catalyst beta

### ISSUE THREAD

**Issue by yacob841** [keepassium/KeePassium#152]
Hello, it might be due to it being a beta or maybe it is intentional and being considered a "different" app but I downloaded the new Catalyst beta and when I went to upgrade to lifetime premium and selected Already Purchased it said that it could not find the purchase.

**Comment by keepassium** [comment]
Hi, thanks for the feedback. 

It's not intentional, but it's not a bug either. It's a mismatch in expectations due to a quirk in TestFlight/iOS beta... There are several factors:

- Premium Forever should not be visible anywhere, it was removed from sale in June 2020. It is not listed in the App Store.
- Beta releases on iOS (installed with TestFlight) show all the in-app purchases, even those that are "not for sale". This seems to be special behavior of StoreKit (system's library for managing in-app purchases). Same app release installed from the App Store shows only available products.
- Mac Catalyst version is not distributed via TestFlight (because it does not exist for Mac apps). So StoreKit behaves as it would in a production app: it fetches only available in-app purchases. That's why that premium version is not visible.

On a related note, I don't think in-app purchases work if the app was not installed from Mac App Store. (At least for KeePassium, where IAPs go only through the App Store.)

**Comment by yacob841** [comment]
I definitely see Premium Forever in the Mac Catalyst version just released. I see Free, Premium at $1.99/month, Premium at $14.99/year, and Premium Forever at $26.99. So not sure how it is still showing up. But to clarify, assuming it works as designed and that option is not there, once it is actually released in stores should the restore purchases restore the Premium Forever from before it was removed?

**Comment by keepassium** [comment]
Hmm, perhaps my understanding of StoreKit is incomplete... And my test machine is stuck on "Contacting AppStore..." anyway.

> once it is actually released in stores should the restore purchases restore the Premium Forever from before it was removed?

Restore purchases already restores Premium Forever on iOS, even though it is marked as not-for-sale. The question is whether macOS would fetch previous purchases made on iOS. If universal purchases work as I think they do, then yes, it should be possible.
