### ISSUE TITLE
iPhone: incorrect letters are entered by a hardware key

### ISSUE THREAD

**Issue by SommerEngineering** [keepassium/KeePassium#168]
**Description**
In the iPhone version of the app, incorrect letters are entered by a hardware key

**How to reproduce**
1. Prepare a KeePassXC database on a regular computer (fill in test data, set password)
2. Set the password as static password on a Yubikey or Onlykey
3. Test the unlocking on the regular computer
4. Copy the KeePassXC database to the iPhone
5. Add it to KeePassium
6. Open the database with KeePassium
7. Insert the Yubikey
8. Press the button
9. The password gets entered
10. KeePassium tries to unlock the database
11. Unlocking fails
12. Press the "eye" icon to see the actual typed password
13. A complete different password was typed :slightly_frowning_face: 

**Expected behavior**
The correct password was typed and KeePassium is able to unlock the database. When I repeat the exact same steps on my iPad Pro, it works though!

**Environment:**
 - Device: iPhone 12 Pro
 - OS: iOS 14.6
 - App Version: 1.24.87

**Additional context**
- When I repeat the exact same steps on my iPad Pro, it works though!
- Thus, it is an iPhone-only issue
- I thought it might be the typing speed. I have therefore configured the Yubikey and Onlykey to type very slowly. Unfortunately this does not change anything.
- I thought it was because the key was using too much power. I therefore connected a charger at the same time. Unfortunately, this also does not change anything.
- And of course, I also tested what happens when I enter the password myself. With the on-screen keyboard it works without any problems. I can also enter the password correctly with an external USB keyboard.
- It appears as if the virtual keyboard of the Yubikey and the Onlykey have a different language with different key codes. However, it is then surprising that it works with the iPad and any other computer.

**Comment by keepassium** [comment]
Hi, thank you for the detailed description! Since you mentioned an iPad Pro, I assume you use a YubiKey 5Ci. 

There are several factors that might explain the difference.

Firstly, the YubiKey emulates a keyboard by sending scan codes to the device. The mapping between scan codes and actual symbols [depends](https://www.yubico.com/blog/yubikey-keyboard-layouts/) on the keyboard layout. For example, the same scan code produced by the YubiKey can become either `@` (with US English layout) or `"` (with German layout). So make sure that both your iPhone and iPad have the same keyboard layout active.

Secondly, it might depend on the physical interface. For the iPad Pro, the key goes via USB-C. For the iPhone, it goes via the Lightning port. This might contribute to the difference as well.

In general, however, this is not a KeePassium issue. Try the reproduction steps on any other app — most likely, you'll see the same effect. I'd vote for the system's keyboard layout as the primary reason.

**Comment by keepassium** [comment]
Ok, since there are no updates, I assume the issue is resolved. If this is not the case, feel free to reopen.
