### ISSUE TITLE
AutoFill extension crashes on opening DB

### ISSUE THREAD

**Issue by ixs** [keepassium/KeePassium#172]
**Description**
When trying the IOS Password AutoFill extension, the extension will crash at around 90% of the opening process.
Database file is only about 500kb big and is using AES-KDF which makes me suspect that https://keepassium.com/articles/autofill-memory-limits/ does not apply.

**How to reproduce**
Open website, select passwords, select file, watch progress bar go to 90%, crash.

**Screenshots**

https://user-images.githubusercontent.com/214768/126484888-1dc77364-3cb8-430b-8702-affe08cec609.mp4

**Environment:**
 - iPhone SE 2020
 - iOS 14.7
 - KeePassium v1.24.87 Pro

Any suggestion how to debug this best?

**Comment by keepassium** [comment]
The loading progress is split in [these phases](https://github.com/keepassium/KeePassium/blob/79b09cd1955dee1fe4c40aefeba15bd2a5dd7943/KeePassiumLib/KeePassiumLib/db/kp2/Database2.swift#L102):
- 60% — key derivation
- 20% — decryption
- 5% — reading/verifying data blocks
- 5% — decompressing gzip'ed data
- 5% — parsing XML
- 5% — resolving references

So crashing at 90% implies the problem happens during the XML parsing step. Which means that:

- Either the XML content is terribly broken and the parser crashes — which is unlikely. (And I assume the same file loads in the app itself just fine.)
- Or XML parsing causes a memory overflow that KeePassium cannot handle gracefully (with an error message).

The second one is most likely. KeePassium uses a DOM parser, so it is quite memory heavy. (I know, not the smartest decision. In my defence, AutoFill API did not even exist at the time...) Moreover, parsing is implemented as a synchronous step, so AutoFill cannot interrupt it in case of low memory notification.

Does your database have `kdbx3` format by any chance? There file attachments are stored directly in XML (as base64-encoded strings), so they all pass through the XML parser. And if attachments are easily compressible (e.g. text), a 500 KB database might become a 10 MB XML, plus ~10 MB for the parsed DOM, plus ~10 MB for the app's data model.

So if you have a kdbx3 database, try converting it to kdbx4 (in KeePass or KeePassXC → Database settings).

To get more info about the crash, check system settings → Privacy → Analytics & Improvements → Analytics Data → search for "KeePassium" and it should show relevant crash logs. The don't contain any private info, so feel free to attach one here.

_N.B. An important caveat: the main KeePassium app and its AutoFill module have separate/independent file lists. (Due to a technical limitation on iOS.) So when you add/remove/re-add a database to the app itself, the AutoFill does not know anything about it and keeps using the old database. So when testing kdbx4, make sure that AutoFill actually refers to the correct database._

**Comment by ixs** [comment]
Thanks for the quick reply.

> So crashing at 90% implies the problem happens during the XML parsing step. Which means that:
> 
> * Either the XML content is terribly broken and the parser crashes — which is unlikely. (And I assume the same file loads in the app itself just fine.)

The file loads correctly in the app.

> * Or XML parsing causes a memory overflow that KeePassium cannot handle gracefully (with an error message).

That seems more likely.
If I save the file uncompressed, I get a 24,2MB file.

If I empty the recycle bin in the database, I get a 422KB file that does not lead to a crash of the AutoFill extension.

> The second one is most likely. KeePassium uses a DOM parser, so it is quite memory heavy. (I know, not the smartest decision. In my defence, AutoFill API did not even exist at the time...) Moreover, parsing is implemented as a synchronous step, so AutoFill cannot interrupt it in case of low memory notification.

Based on your explanation and my observation, this seems likely.

> Does your database have `kdbx3` format by any chance? There file attachments are stored directly in XML (as base64-encoded strings), so they all pass through the XML parser. And if attachments are easily compressible (e.g. text), a 500 KB database might become a 10 MB XML, plus ~10 MB for the parsed DOM, plus ~10 MB for the app's data model.

No, this is a `kdbx4` Format. It started out as kdbx3 but was converted long ago.

> To get more info about the crash, check system settings → Privacy → Analytics & Improvements → Analytics Data → search for "KeePassium" and it should show relevant crash logs. The don't contain any private info, so feel free to attach one here.

Interestingly, I do not find anything in that list under KeePassium. Is the AutoFill extension logging analytics data under a different name?

**Comment by keepassium** [comment]
> Interestingly, I do not find anything in that list under KeePassium. Is the AutoFill extension logging analytics data under a different name?

(Just to be clear, crash logs are created by the system. KeePassium's own diagnostic log lives only in the RAM. This complicates crash analysis, but simplifies the privacy policy.)

Apparently, memory-related crashes are logged as [JetsamEvent](https://developer.apple.com/documentation/xcode/identifying-high-memory-use-with-jetsam-event-reports). 

I have replicated the crash with a large-XML database, and here's the relevant part of the JetsamEvent log:

    {
      "uuid" : "d75fc452-53f0-31b1-9b43-59e00ddfa507",
      "states" : [
        "frontmost"
      ],
      "killDelta" : 13403,
      "genCount" : 0,
      "purgeable" : 9,
      "age" : 2858291763,
      "fds" : 25,
      "coalition" : 736,
      "rpages" : 7680,
      "priority" : 10,
      "reason" : "per-process-limit",
      "physicalPages" : {
        "internal" : [
          7659,
          2
        ]
      },
      "freeze_skip_reason:" : "none",
      "pid" : 654,
      "cpuTime" : 2.0955360000000001,
      "name" : "KeePassium AutoFill",
      "lifetimeMax" : 7680
    },

The "reason" field points squarely to the 120 MB (or so) memory limit... I guess you have the same reason listed?

**Comment by keepassium** [comment]
Ok, it seems we are good here.
