### ISSUE TITLE
Application does not react to clicking after scrolling/animations

### ISSUE THREAD

**Issue by vit9696** [keepassium/KeePassium#181]
**Description**
For some reason the application often misses mouse clicks. Most commonly this happens right after scrolling the list or right after the animation, e.g. during the navigation.

**How to reproduce**

1. Open preferences.
2. Scroll the list and then click on any entry right after completing to scroll.
3. Sometimes it will do nothing, and a second click will be needed to actually trigger the element.

**Expected behavior**
All the elements should be responsive, and I should be able to navigate over preferences.

**Screenshots**
I recorded a [video](https://user-images.githubusercontent.com/4348897/130354739-f7908bc4-b09a-4f94-9730-d496b8b51dfc.mp4) showing the bug.

**Environment:**
 - Device: Mac
 - OS: 11.5.1
 - App Version: master

**Additional context**
In case you wonder why the scrolling is so smooth, I use an ordinary Logitech mouse with Smoothscroll. Completely removing Smoothscroll does not affect the problem anyhow, it is still easily reproducible for me.

**Comment by keepassium** [comment]
I've just spent some time testing this, and it's a peculiar one... 

N.B.: In debug build, Preferences self-refresh every second. To exclude this factor, I started testing in the About screen. Then made a new app with `UITableViewController` populated with 1000 rows, just to have a clean test.

Results: 
- Mouse: during the scrolling animation, clicks are completely ignored. After reaching the top or bottom of the list, clicks are registered only after mouse wheel stops spinning (Logitech inertial wheel). Once both animation and the wheel stop, clicks are registered normally.
- Trackpad: when scrolling, touching the trackpad stops scrolling. Pressing the trackpad registers the click, as it should. And since pressing is always preceded by a touch, clicking on the trackpad 1) stops scrolling, 2) registers the click. So, with a trackpad everything works ok.

The same behavior is reproducible in Apple's own Catalyst app, Podcasts: mouse clicks are ignored while spinning, pressing the trackpad stops scrolling and clicks properly. 

Resume: seems to be a Catalyst bug. Given that no Apple hardware has a scroll wheel, I guess they just did never tested Catalyst apps with any other mouse :)

**Comment by vit9696** [comment]
Maybe file an FB on this? There is a fair chance it gets looked at eventually.

**Comment by vit9696** [comment]
> clicks are registered only after mouse wheel stops spinning

Actually, I do not believe it is the case here, they rather get registered a little after the mouse wheel stops. This is why the issue feels so confusing. There is no wheel/animation active but the click fails to register. If you have a test app, uploading it and/or filing a FB report will help (FB number would be appreciated).

**Comment by keepassium** [comment]
> Actually, I do not believe it is the case here, they rather get registered a little after the mouse wheel stops. 

Yeah, it does feel a bit odd.

I've noticed another oddity. Open the settings, then click on some sub-page (e.g. "What's new"). Scroll it a few lines up and down (keeping the finger on the wheel, just move it back and forth). While doing this scroll-swinging, press `Esc` to go back to the settings. 

It won't be scrolling. Only when you pause for a moment, then it will start scrolling normally. It is as if the previous view controller captures scroll events. Same issue in Podcasts.

**Comment by keepassium** [comment]
> Maybe file an FB on this? There is a fair chance it gets looked at eventually.

[rdar://FB9554677](https://openradar.appspot.com/FB9554677)

--

Another observation: if I wait just a fraction of second longer than intuitive, there are no missed clicks. 

So as a final hypothesis, I've checked whether this might be a perception issue. Maybe we feel the animation is finished while it is still ongoing?

When popping a view controller, the time between underlying VC's `viewWillAppear` and `viewDidAppear` is 510-520 ms (according to log timestamps). According to screen recording, the actual animation takes 30 frames (at 60 fps), that is 500 ms. Seems consistent. 

However, the animation slows down at the end. The first 15 frames the VC slides most of the width, up to the scrollbar. Sliding the width of the scrollbar takes the other 15 frames. That's 250ms of our brain thinking the animation is complete, while it still crawls to the end... 

Given the 250 ms lag and an average human reaction time of [~270ms](https://humanbenchmark.com/tests/reactiontime), the hypothesis cannot be rejected. Unfortunately, with the available equipment it cannot be confirmed either... 

Anyway, analyzing this issue took way more time than it deserves... Most users will never encounter it, and of those who will, only few would notice. As much as I like polished experience, it's time to move on...
