### ISSUE TITLE
Update check and/or Homebrew cask

### ISSUE THREAD

**Issue by qqvm** [keepassium/KeePassium#197]
**Describe the feature you'd like**
I would like to request the update check feature for the desktop application.
Also it would be nice to have the ability to install KeePassium via Homebrew.

**Comment by keepassium** [comment]
Thank you for the feedback! 

As you know, KeePassium for macOS is currently in beta testing. It is published on GitHub because there is no TestFlight for macOS 11.

Once the app is released, it will be distributed via the Mac App Store. This is necessary because in-app purchases are tied to Apple's infrastructure, and the app would be crippled without it. The App Store will also cover the "update check" part.

**Comment by aniqueta** [comment]
@keepassium Wondering if we can get a macOS TestFlight release? Thanks.

**Comment by keepassium** [comment]
@aniqueta, TestFlight releases are reviewed by Apple, so they would be lagging. But this is the only way to get automatic updates in beta, so I guess I will have to start submitting them :)

**Comment by keepassium** [comment]
It is already approved for Mac TestFlight, feel free to join: https://keepassium.com/beta
