### ISSUE TITLE
Feature request: Internationalization and localization

### ISSUE THREAD

**Issue by dotWee** [keepassium/KeePassium#20]
First of all, thanks for your incredible work. You’re doing **god’s work**. 

I would love to contribute and maintain a translation into the German language, but it seems that all strings are static and distributed over the whole source code. Maybe think about moving them into separate and translatable resource files.

Official references and documentation provided by Apple:
- [About Internationalization and Localization](https://developer.apple.com/library/archive/documentation/MacOSX/Conceptual/BPInternational/Introduction/Introduction.html#//apple_ref/doc/uid/10000171i-CH1-SW1)
- [Internationalization and Localization for iOS](https://developer.apple.com/library/archive/samplecode/InternationalMountains/Introduction/Intro.html#//apple_ref/doc/uid/DTS40008756)

**Comment by keepassium** [comment]
Thanks, @dotWee !

The good news is that most of the groundwork is already done. All user-facing strings are either in storyboards (that are localizable at file level), or wrapped into `NSLocalizedString`. (Except diagnostic messages, though, as they won't be seen by most people.) 

In theory, generating files for translation should be as easy as ticking a few checkboxes in Xcode. 

In practice, however, I first have to ensure that localization context comments are both meaningful and consistent. That is, every “Done” is described as either an action or a state. And whenever a description says “This is one of the possible values of AppLock timeout setting” - to make sure that AppLock was not renamed to something else over the last few months.

So, to streamline the localization as much as possible, I usually ~eat my own dog food~  first translate the app myself (to Russian) and improve the localization comments along the way. This makes other translator’s life a bit easier. 

Unfortunately, for the moment this makes me the bottleneck, as I am completely occupied to release the app this month...

**Comment by dotWee** [comment]
Seams reasonable, so I’m ready to contribute my translation when you are. Just make sure to let us people know.

Thanks again for your work!

**Comment by Thunder33345** [comment]
do update us when you are ready to recieve contributions of translation!

**Comment by Vistaus** [comment]
I too am ready to contribute :)

**Comment by keepassium** [comment]
Ok, the preparatory work took waaay more time than I expected, but KeePassium is finally [ready for localization](https://github.com/keepassium/KeePassium-L10n)!

The collaborative online translation platform is kindly provided by [Crowdin](https://crowdin.com). Kudos to @Andrulko for making it available to KeePassium for free!

In the best traditions of [eating your own dog food](https://en.wikipedia.org/wiki/Eating_your_own_dog_food), I have used the platform to translate the app to Russian. This process highlighted a few ambiguous phrases and unclear localization hints. The discovered issues have been fixed, but there will likely be more. Please use Crowdin discussion board and/or comments to raise any specific translation issues.

_P.S. Due to legal formalities, [KeePassium-L10n](https://github.com/keepassium/KeePassium-L10n) exists as a separate project published under the MIT license. This formally makes it independent from KeePassium and moves the collaborative localization effort from the scope of the [GPL-vs-AppStore dispute](https://github.com/keepassium/KeePassium#license), so we don't have to bother with copyright transfer forms..._

**Comment by Andrulko** [comment]
@keepassium Congrats with the official l10n launch! Please add Ukrainian, too :)

**Comment by keepassium** [comment]
@Andrulko Thanks! I’ve added Ukranian and a few other languages, just in case :)

**Comment by dotWee** [comment]
Nice to hear this, I’ve already started translation into the German language and will complete it fully within in the next days. Thanks for making this possible!
