### ISSUE TITLE
New attachments seem corrupted until database is reloaded

### ISSUE THREAD

**Issue by layandreas** [keepassium/KeePassium#211]
**Description**
.pfx file is corrupted after saving as attachment.

**How to reproduce**
1. Create database
2. Create entry
3. Add .pfx file as attachment
4. Save database
5. Download .pfx from databse

**Expected behavior**
The saved file should not be corrupted.

**Screenshots**

Original .pfx file:
<img width="558" alt="Screenshot 2021-12-17 at 17 02 16" src="https://user-images.githubusercontent.com/79149948/146574589-99df6b95-21ca-4efe-b745-f0842e8bf83f.png">

File from database (file size is actually slightly less than the original file):
<img width="543" alt="Screenshot 2021-12-17 at 17 08 56" src="https://user-images.githubusercontent.com/79149948/146574626-0858ebbe-b517-48c0-92a2-721aa4a6a613.png">

**Environment:**
 - Device: iphone 12, ipad air, macbook air
 - OS: any
 - App Version: 1.29

**Comment by keepassium** [comment]
I can reproduce this, definitely an issue.

When saving the database, KeePassium gzip-compresses the attachments. When loading the database, the app decompresses them. Apparently, for new files compression applies to the actual data (instead of a copy). That's why the file looks slightly smaller and starts with gzip signature (`1F8B08`).

Once you close and reopen the database, all the attachments are decompressed and look fine. (I guess that's why you closed the issue?)

I have also tested adding two attachments in a row, and the first one was compressed only once. After reloading the database both attachments were fine.

So while not a critical issue (attachments in the database are fine), this is still a very valid issue. I will get this fixed. Thanks, Andreas.
