### ISSUE TITLE
Need help: KeePassium suddenly asks for password

### ISSUE THREAD

**Issue by loeffelpan** [keepassium/KeePassium#214]
I‘m wondering why KeePassium sometimes asks for the db password. Nothing changed. Masterkey should be valid. Face/Touch-ID for the App Passcode was successful. Timeout is set to „Never“.

Most times that work. Sometimes/Suddenly not.

Can you please list the cases KeePassium will ask for db password? Maybe I‘m able to figure it out.

**Comment by keepassium** [comment]
Which version?

**Comment by loeffelpan** [comment]
That happened over longer period.
Shoud matter more than one version.

Latest was with 1.29.100.

**Comment by keepassium** [comment]
I have asked about the version because there was a [relevant fix](https://github.com/keepassium/KeePassium/blob/master/CHANGELOG.md#130101---2021-12-10) 1.30.101 (beta): 
> AutoFill could lock up the database when running low on memory [thanks, Tim]

In general, these are the reasons why KeePassium can have the database locked:
- Wrong app protection passcode entered
- Database timeout
- The app was offloaded then restored
- The device was restored from iCloud backup
- User transitioned to a new device
- There was a breaking change in how KeePassium stores master keys

The latter happened in 1.28, where stored keys were additionally encrypted by Secure Enclave. The new version was supposed to automatically convert stored master keys into new format, but due to a bug it failed to read the old data. I got this fixed in 1.30.101, and paused automatic rollout of 1.29.100 (the latest App Store version) until the fixed version is beta-tested and ready for the App Store.

**Comment by loeffelpan** [comment]
Thanks.
So maybe lastest times this happened was due to that bug after updating to 1.29.100 due to that key conversion.

I‘ll have an eye on it next time that happens and (hopefully not) open another issue.

Happy new year and stay healthy.
