### ISSUE TITLE
Hide TOTP fields from the item view

### ISSUE THREAD

**Issue by plus-or-minus** [keepassium/KeePassium#218]
**What can be improved?**
Hide "TOTP Seed" and "TOTP Settings" fields from the item view since the "TOTP" field is present. The fields are used to calculate a one-time password token so they aren't that useful. They're extra noise that may confuse non-technical users.

**The solution you'd like**
The "TOTP Seed" and "TOTP Settings" will be editable in the edit form but hidden when viewing the item.

**Alternatives you've considered**
Are there any alternative solutions you've considered?
No

**Additional context**
None

**Comment by plus-or-minus** [comment]
Related to #219

**Comment by plus-or-minus** [comment]
Will you accept a PR for this?

**Comment by Taxyovio** [comment]
This is a pretty bad change too. The entry form shouldn’t change randomly based on what a non-technical user deems confusing!

If these are so confusing for non-technical users, the standard of users is just becoming too low. Why not hide everything besides username and password?

This hiding makes a significant more difficult to copy the seed. Technical users might also get “confused” where the TOTP comes from when there’re no configuration fields.

**Comment by keepassium** [comment]
@Taxyovio, the difference between entry viewer and entry editor is inevitable. Empty fields (both standard and custom) are visible in the editor, but not in the viewer. In contrast, generated TOTP exists only in the viewer, but not in the editor.

In this case, showing both the generated TOTP code and TOTP configuration field seems redundant. The only purpose of the latter is to make the former possible.

> This hiding makes a significant more difficult to copy the seed. 

I would argue that copying the seed is a negligibly rare action. 

Moreover, copying the seed got complicated from "just tap" to "tap Edit → double-tap the seed → tap Copy". At the same time, copying a previously off-screen field got simplified from "scroll → tap" to "just tap". The improvement itself is smaller, but considering the frequency of both action across the user base, copying the seed is negligible.

> Technical users might also get “confused” where the TOTP comes from when there’re no configuration fields.

At first, perhaps. Then the user opens the entry editor, understands the logic, and carries on with their life — with less visual noise and more screen estate for other fields.

**Comment by Taxyovio** [comment]
I promise I’ll see myself out after this one.

If you really care about redundancy, you wouldn’t put “One-time password" in front of “TOTP”. Heck it’s not even the correct full term for TOTP. If you believe people should just figure things out and move on with their lives, why not apply the same idea consistently in every design choices?

As soon as these baby-catering changes hit the App Store, I’m done with it. It’s your app and you can ruin it however you like. I just feel disappointed after promoting Keepassium across forums and YouTube due to its aesthetics and design.

**Comment by keepassium** [comment]
@Taxyovio, you might want to turn "pushy" down a notch. Every single person is biased by their preferences, use cases and constraints. If we made a poll now, the opinions would have been all over the place: show them, hide them, make it an option in the settings, and so on.  (In #219, three people offered *five* different options for naming the generated code.) There are *many* opinions, and most people are humble enough to understand their opinion is just a single point, not the single most important one.

Someone has to make a decision, and some users will necessarily be disappointed. I make these decisions not only because this is my project — I am also in the unique position to receive feedback from *multiple* users, a glimpse of the bigger picture. This enables me to approximate the optimal solution across the whole user base, not centered to any single user (myself included). 

> As soon as these baby-catering changes hit the App Store, I’m done with it. 

Well, this was bound to happen eventually… Thank you for your input and good luck!

**Comment by Taxyovio** [comment]
Of course everyone has an opinion. Some has more solid reasoning than others. If you believe everyone’s opinion had the same weight, it’s your golden pill to swallow. 

I’ve been intentionally being brutal in my comments. Not because I think this makes it easier to communicate, but because my opinions are strongly grounded. I would have thought you’d rather honest opinions than friendly gossips. I could pretend to be humble and pretend every casual user has a say in this. But I don’t think that’s genuine. It’s also your choice if you make decisions based on my harsher tone. It’s also your strategy if you want to appeal to casual users. 

I have said too much already and I’m tired of this conversation too. My points are very clear. I won’t even hypocritically say “good luck” as I just really don’t like the direction keepassium is heading to.
