### ISSUE TITLE
Rename "TOTP" to "Verification code" or "One-time password"

### ISSUE THREAD

**Issue by plus-or-minus** [keepassium/KeePassium#219]
**What can be improved?**
Rename the "TOTP" to an obvious description for non-technical users. They may not know what TOTP is.

**The solution you'd like**
Change the label to "Verification code" to match iCloud keychain

**Alternatives you've considered**
Appending the acronym's definition to the label "TOTP (Time-based one-time password)"
1Password uses "one-time password"

**Additional context**
None

**Comment by keepassium** [comment]
Good point, thanks!

I think the "One-time password (TOTP)" would offer the best balance: informative enough for non-technical users, clear enough for advanced users. (Plus, allows differentiation once [HOTP](https://github.com/keepassium/KeePassium/issues/173) is added.)

**Comment by Taxyovio** [comment]
This change is so OCD inducing. Besides it it’s clearly redundant to have both the full term and the acronym, it’s also not properly capitalised in title case as “One-Time Password” to be consistent with “User Name”. All other keepass apps are labelling it as “TOTP”. I think it should have been kept as “TOTP” or “Time-Based One-Time Password”.

The argument that non-technical people would be confused is so weak. This TOTP field is the only blinking and changing field giving you a dynamic code. It’s automatically copied in autofill too.

I don’t even think non-technical person should ever bother with keepass as they’re likely to mess up the database. If you’re supervising some non-technical relative, isn’t it also your responsibility to teach them the basic terms?

**Comment by keepassium** [comment]
> it’s clearly redundant to have both the full term and the acronym

@Taxyovio, I would happily have it as concise as "One-Time Password", but eventually there will be HOTPs as well. Hence the need for the acronym, too.

The long version "Time-Based One-Time Password" would reduce the clarity and would be equally annoying both for expert and non-expert users. (Expert: "Just call it TOTP!" Non-expert: "I need a one-time password, but this one is a _time-based_ one. Is this what I need?")

> If these non-technical people can’t even google an acronym, why not change “URL” to “website links” as well? There’s no bottom line for how much to support non-technical users.

Being "technical" is not a yes/no state. An otherwise technical user might have never encountered the acronym before. I know, because that was me some 5 years ago. So there are definitely users — both technical and beginner — who would appreciate the more human-friendly text.

"One-Time Password (TOTP)":
- Pro: expert users recognize it by "TOTP" (and can distinguish from "HOTP")
- Pro: casual users understand it by "one-time password"
- Pro: casual users learn the acronym (speaking of the responsibility to educate the users…)
- Con: the acronym feels redundant

In my opinion, the benefits outweigh the eyesore of 6 extra characters.

**Comment by Taxyovio** [comment]
We clearly just have different options on this. I don’t think it’s worth a forever eyesore to probably clarify the situation for 1 in 1000 users in their first time encounter of the term. 

I can’t even think of any situation where a user would be confused because users have to set up TOTP and write in the settings and seeds themselves. Even if the database is shared, is there really possible for any decently intelligent human being to not be able to figure out that blinking field is the one-time password? Is there anyone who really can’t google it if they don’t know the term? Speaking of educating users, I’m talking about the situation where a technical person is responsible to educate if he is sharing a database. Say I’m sharing my database with my mom, I would be responsible to educate her what TOTP is. I wouldn’t ask for you to accommodate by adding an eyesore in an otherwise perfectly aesthetically pleasing app.

**Comment by keepassium** [comment]
@Taxyovio , I respect your opinion. Let us also respect our time. This discussion can continue infinitely, and after some 5-10-20 hours one of us might even convince the other. I am sure both of us have better use for that time, let's focus on that.

**Comment by Taxyovio** [comment]
Sure. I’m not your only customer and you’re not the only app. We can choose what to focus on.

**Comment by keepassium** [comment]
Thanks again for the feedback, everyone. 

After some more reflection, I have updated the field name to "One-Time Password", dropping the acronym part. As long as HOTP is not implemented, all the OTPs are time-based anyway. And even when HOTP _is_ implemented, the user probably won't care whether the generated code is TOTP or HOTP.

The difference, however, would become important when the same entry defines both a TOTP and HOTP. In such cases, KeePassium would use field names with acronyms. I assume these would be rather rare cases :)
