### ISSUE TITLE
Add support for TOTP defined in URI format

### ISSUE THREAD

**Issue by Nu11u5** [keepassium/KeePassium#23]
Per [the feature list](https://github.com/keepassium/KeePassium#features) and #7, #8 KeePassium supports TOTP.

I have a KDBX file created in https://app.keeweb.info/ that has been imported into KeePassium.  Entries have records labeled "otp" with data in the standard URI format "`otpauth://totp/{label}?secret=`...".  This shows the rotating TOTP code correctly in KeeWeb but in KeePassium all I see is the protected URI text.

Additionally I cannot see how to create a new TOTP record in KeePassium.  Am I supposed to enter the URI manually - no support for QR codes?

How is TOTP supposed to be setup and used?

**Comment by Dragonblitz10** [comment]
If we have a TOTP feature where is it located?

**Comment by keepassium** [comment]
@Nu11u5, yes, since [beta 16](https://github.com/keepassium/KeePassium/blob/master/CHANGELOG.md#1016-stealth-beta---2019-03-12) KeePassium can show TOTP codes stored in KeePassXC format (`TOTP Seed` and `TOTP Settings` fields). I thought it was the only format used by KeePass apps. Guess I was wrong :)

At the moment TOTP support is view-only (so the readme is a bit misleading). Anyway, creating/scanning them is certainly in my backlog.

@Dragonblitz10, you can already store key pairs as entry attachments. Generating them, however, is beyond the scope of a password manager — this is better done by specialized utilities.

**Comment by Nu11u5** [comment]
@keepassium This should be the documentation on the URI format (looks to be created by Google):

https://github.com/google/google-authenticator/wiki/Key-Uri-Format

All of the TOTP QR codes that I've scanned into Keeweb have used this format.
