### ISSUE TITLE
Support webdav protocol

### ISSUE THREAD

**Issue by dtantono** [keepassium/KeePassium#247]
**Describe the feature you'd like**
For better integration and make sync kdbx easier between platforms. Support for webdav in cloud storages is good

And *why* you need it — that is, how it would make your life better.
it can make sync kdbx database easier

**Comment by keepassium** [comment]
Good news, it is already in [beta testing](https://keepassium.com/beta) :)

**Comment by dtantono** [comment]
@keepassium that is good. I hope this new webdav feature can support with 2fa enabled such as PCloud/Icedrive

**Comment by vit9696** [comment]
@keepassium, will the source code be eventually available? My understanding is that Testflight is currently Apple Silicon exclusive and cannot be used on x86 hardware.

**Comment by keepassium** [comment]
> I hope this new webdav feature can support with 2fa enabled such as PCloud/Icedrive

@dtantono, not yet, but sometime later.

> will the source code be eventually available? 

@vit9696 , sure, in a day or so.

**Comment by keepassium** [comment]
It seems I've messed up while squashing the commits, so [Add in-app WebDAV support](https://github.com/keepassium/KeePassium/commit/3d0800a10017ba4f450e02e2171e50e664cf460a) kept the date of the branch's first commit (3 January 2022) instead of the last one. As a result, it gets pushed down the GitHub's commit timeline — which looks suspicious, but was not intended. Sorry about that. (Looks ok in GUI clients, though.)
