### ISSUE TITLE
The file couldn’t be opened on macOS 12.6

### ISSUE THREAD

**Issue by Eitot** [keepassium/KeePassium#258]
**Description**
A database file that I store in iCloud Drive is not opening anymore on macOS. It worked fine until some weeks ago, but I cannot say whether this is a problem in the latest version of KeePassium. It works without any issues on my iPhone XS running iOS 16. Also the backup files (the newest I have was created on 13.09.2022) can be opened just fine.

I have also tried to copy the file out of iCloud Drive to my Documents directory instead, but it won't open there either.

**How to reproduce**
1. Within Keepassium, when I click on the + button and select the database, nothing happens (also no alerts or dialogs).
2. When I open the database file directly in Finder, the following error alert appears:
<img width="901" alt="Screenshot 2022-10-01 at 12 41 22" src="https://user-images.githubusercontent.com/15073177/193405689-bed4e692-1beb-4612-812b-69bafec4075c.png">

**Environment:**
 - Device: MacBook Pro (14-inch, 2021) with M1 Pro 
 - OS: macOS 12.6 (21G115)
 - App Version: 1.36.116 (iOS version via Mac App Store)

**Additional context**
[Diagosntic log](https://github.com/keepassium/KeePassium/files/9690101/log.txt)

**Comment by keepassium** [comment]
I have received a similar report two weeks ago, that it was impossible to add a database from iCloud Drive using KeePassium's UI. The app would just freeze. Adding of local files worked, though. It was also macOS 12.6 (21G115) and KeePassium 1.36.116, but I could not reproduce the issue.

As a test, can you install [1.35.114](https://github.com/keepassium/KeePassium/releases/tag/1.35.114) and see if the issue remains there? Thanks!

**Comment by keepassium** [comment]
Thank you for the update.

> Nevermind, the same error is back. There was briefly an error message that stated that the backup is unreachable.

Do you get the same error with 1.35.114? If yes, does the error remain after reboot?

**Comment by aztira** [comment]
> I have received a similar report two weeks ago, that it was impossible to add a database from iCloud Drive using KeePassium's UI. The app would just freeze. Adding of local files worked, though. It was also macOS 12.6 (21G115) and KeePassium 1.36.116, but I could not reproduce the issue.

I'll chime in here, as the similar report Andrei mentions probably was from me. I could not open my current database in i-Cloud, however, any backup files opened just fine from within KeePassium. Also, double-clicking any DB in Finder opened it in the app (which unfortunately does not help in the Safari extension). The database also opens without problem in KeepassXC and in KeePassium 1.36.116 on my iPhone (iOS 16.0 20A362).

Re-moving KeePassium using App Cleaner and re-installing from the App Store resolved the issue for now even after a reboot - I will report back if something changes.

KeePassium v1.36.116 on MacOS 12.6 (21G115) on an M1 MBP

**Comment by keepassium** [comment]
Thanks, everyone!

@aztira , yes, I was referring to your email.

@Eitot , has the error resurfaced since?

Also, as a wild guess: did you happen to install any other KeePass-related app before the issue started? On iOS, there was a frequent problem early on that the system assigned "ownership" of .kdb/.kdbx files to the last-installed compatible app. All the earlier apps were suddenly deemed incompatible and could not pick database files — the system greyed them out as "incompatible". As a workaround, KeePassium now [declares](https://github.com/keepassium/KeePassium/blob/master/KeePassium/Info.plist)  that it understands "KeePassium databases", "MiniKeePass databases", "Strongbox databases", etc. 

If macOS 12.6 introduced the same issue, perhaps I only need to declare KeePassium as compatible with "KeePassXC databases", "KeeWeb databases", etc :)

**Comment by keepassium** [comment]
@Eitot , thanks! So I guess we'll write it off as a transient macOS glitch then...
