### ISSUE TITLE
Add support for entry placeholders

### ISSUE THREAD

**Issue by mateuszdrab** [keepassium/KeePassium#260]
**Description**
I have some entries where the `ota` field starts like this `otpauth://totp/xxx::{S:eMail}?` -  Keepassium displays the whole URL, no TOTP code

This is because I have a different username and store emails in a field called `eMail`.

KeePassOTP generates the otaurls in the format containing the reference and it works fine in KeePass and KeePassXC.

**How to reproduce**
- add a keepass entry with username set to `{S:eMail}` and add the `eMail` field
- add an OTP config using KeePassOTP

**Expected behavior**
OTP is displayed

**Environment:**
 - Device: iPhone 12 Pro Max
 - OS: iOS 16
 - App Version: 1.36.116

**Comment by keepassium** [comment]
Thank you and sorry for the delay.

The reason is that, `{S:}` is a [placeholder](https://keepass.info/help/base/placeholders.html) rather than a reference. Semantically they are very similar, but references start with `{REF:`. At the moment, KeePassium supports references but not placeholders. 

I will requalify this as a feature request then, if you don't mind.
