### ISSUE TITLE
macOS: it's possible to add entries when KeePassium is locked using cmd+n

### ISSUE THREAD

**Issue by latvia234** [keepassium/KeePassium#280]
**Description**
I’ve enabled the ability to unlock the vaults with a passcode. When the vault seems locked and I am at the screen “Unlock KeePassium" I hit keyboard shortcut cmd+n. It seems to be possible to add an entry. When saving it is visible inside the vault.

Is the word “unlock” really a good description of what is happening? Because if I can add an entry, is the vault really locked or not?

**Expected behavior**
Database is locked when I am at the screen “Unlock KeePassium", so it's not possible to add entries via cmd+n

**Comment by keepassium** [comment]
This should have been [fixed in 1.41.125](https://github.com/keepassium/KeePassium/blob/master/CHANGELOG.md#141125---2023-02-15). Which version of KeePassium do you run?

**Comment by vit9696** [comment]
@keepassium, could you please also confirm that this new build guarantees that once the database is locked:

* it cannot be read or modified programmatically
* all the secrets are erased from RAM

The question is raised because I only see that the menu entry is hidden in the changelog. One can find another bug for this or can read application memory.

**Comment by keepassium** [comment]
> @keepassium, could you please also confirm that this new build guarantees that once the database is locked:
> - it cannot be read or modified programmatically
> - all the secrets are erased from RAM

We need to distinguish the "app lock" and "database lock" concepts here. These two locks are represented by separate sections in the app settings ("App Protection" and "Data Protection"). This issue is about the first one ("KeePassium is locked"), while your question seems to refer to the second one ("database is locked").

- App lock basically covers the app UI with a passcode overlay. If there is an opened database, it will remain opened and in memory.
- Database lock does indeed close the database viewer UI, erases the DB's master key from the keychain (if it was there at all), and finally zero-fills and releases the RAM occupied by DB data (as much as possible with a managed language).

**Comment by keepassium** [comment]
Ok, I will assume the fix has worked out.
