### ISSUE TITLE
Inconsistent thickness of outline UI icons

### ISSUE THREAD

**Issue by FanXiangTM** [keepassium/KeePassium#287]
The 5 buttons at the bottom and the "+" at the top right corner use lines that are too thin and completely incongruous with the UI. Maybe the developers themselves are used to seeing it, but for new users, the first glance at such a rough UI is likely to make them give up. At least, the buttons on the interface should use the same lines

**Comment by keepassium** [comment]
Thank you for the feedback! 

On the one hand, I agree: most of those icons were rendered for iOS 11 and did not change since. They are indeed "light" by SF Symbols standards. However, they should be consistent at that.

On the other hand, can you please give some specific examples of "completely incongruous with the UI"?

**Comment by FanXiangTM** [comment]
> 

My English is not good, the sentence "completely incongruous with the UI" may be my expression is not accurate.
What I mean is that the buttons at different positions on the interface use icons of different thicknesses. For example, the return button "<" in the upper left corner is thick, while the plus sign "+" in the upper right corner is thin, which looks very uncoordinated

**Comment by keepassium** [comment]
Thank you for the explanation. You are right, this needs work. I also realized the issue is much more obvious in dark mode. I will get this fixed (cannot promise high priority, though...)

Thanks again!

**Comment by katullo11** [comment]
I agree. The UI icons need work, and I'm glad they're being rethought.
Please do take into consideration a "bold" version since many developers ignore the possibility of someone using bold text (I would know as a bold text user). Icons should adapt to bold text by implementing thicker outlines to align with the text weight.

Thanks!

**Comment by skaionedev** [comment]
May be you should consider adding an option to fetch icons from urls - that would be nice to have feature

**Comment by keepassium** [comment]
@skaionedev , thanks. That is already enqueued as #164.
