### ISSUE TITLE
direct start of password generator

### ISSUE THREAD

**Issue by cryptosteve2** [keepassium/KeePassium#293]
Am I missing something, or can I only open the password generator when creating a new entry?

It would be nice if it could be started directly via a button.

**Comment by keepassium** [comment]
There is a button at the bottom of the "Databases" screen. 

There is also a "Dice" icon in the context menu of text fields ([demo](https://keepassium.com/blog/2022/06/keepassium-1.34/password-generator-menu.mp4)). But it works only in group/entry editor.

No button in group viewer because its toolbar is already a bit crowded. I will need to rearrange it first.

**Comment by cryptosteve2** [comment]
Uh, "here is a button at the bottom of the "Databases" screen." - never seen that before, I'm always in the open database screen.

This is solved for me. Should I close this issue/feature request?

**Comment by keepassium** [comment]
Great! I'll close.
