### ISSUE TITLE
Autofill didnt work on my iPhone

### ISSUE THREAD

**Issue by the-davinci-code** [keepassium/KeePassium#298]
I created my database in my PC in KeePassXC with default security settings. I downloaded your app, add my database and all works fine and autofill feature too. But after few days I faced with this error.![image](https://github.com/keepassium/KeePassium/assets/130255158/c7e2ac46-59f9-40ec-9d88-a4f59ab3244e)
And I dont understand how its can be, cause I didnt change anything in my database. I checked official guide about this error but in app I cant change database security settings. And I started change it on my PC. I tried to change some options but its still didnt work. After I think that I need create database on iPhone and set the same security settings on my database and after that export it on iPhone. But you know? Its again didnt work. My database have about 40-50 entries and I didnt think that its "large".

**Comment by keepassium** [comment]
Default encryption settings in KeePassXC exceed the 120 MB limit explained in the [relevant help page](https://keepassium.com/articles/autofill-memory-limits/). Simply because KeePassXC does not have an AutoFill module and thus does not face that ridiculous limit. Practice shows, that the limit is rather flexible: sometimes iOS feels generous and allows KeePassium to use more than 120 MB. But on other days it would enforce the limit, sometimes even at a lower threshold.

> My database have about 40-50 entries and I didnt think that its "large".

What matters is the file size, not the number of entries. If you had even a single entry, but with 50 MB of attachments in it — this would not work. In this case, you would need to move attachments to a separate database, as described in the guide: [Reduce file size](https://keepassium.com/articles/autofill-memory-limits/#reduce-database-size).

> And I started change it on my PC. I tried to change some options but its still didnt work.

"Some options" is rather vague, though… Please make sure to follow [the guide](https://keepassium.com/articles/autofill-memory-limits/#tweak-database-settings): 
- KeePassXC → Database → Database Security → Encryption Settings
- Enable the Advanced Settings in lower-left corner
- Reduce _Memory Usage_ to 32 or even 16 MiB
- Click _Benchmark 1.0s delay_ to set the _Transform rounds_
- Click OK to save changes
- Transfer the updated database to the phone
