### ISSUE TITLE
Migration to organization

### ISSUE THREAD

**Issue by Neustradamus** [keepassium/KeePassium#302]
Dear @KeePassium team,

It is possible to migrate the personal account to organization?

Converting:
- https://help.github.com/articles/converting-a-user-into-an-organization/

It is possible to rename this account and create the organization and move/transfer the repository to the organization.

Rename account:
- https://help.github.com/en/enterprise/2.13/user/articles/changing-your-github-username

Create an organization:
- https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/creating-a-new-organization-from-scratch

Transfer a repository:
- https://help.github.com/en/github/administering-a-repository/transferring-a-repository

Like:
- https://github.com/IBM
- http://github.com/gnome
- http://github.com/kde
- ...

**Comment by keepassium** [comment]
Hmmm, but why?

**Comment by keepassium** [comment]
Sure, but this would replace nice and clean `keepassium` with something less concise. What are the benefits of doing so?

**Comment by keepassium** [comment]
> A better management, more options, ...

In comparison to very concrete drawbacks, these benefits are way too vague. [It ain't broke](https://en.wiktionary.org/wiki/if_it_ain%27t_broke,_don%27t_fix_it), so won't fix.

Thanks again for the suggestion, though.

**Comment by keepassium** [comment]
Let me summarize again:

1. The purpose of this account is to provide access to KeePassium source code and related libraries. This already works well as it is.
2. Switching to an organization account would:
	- If converting the account type:
		- Break authorship of commits and comments
		- Make it no longer possible to comment as @KeePassium
	- If transferring to a new org account:
		- Break existing links to the repo
	- If current account renamed, then a new one created:
		- Risk losing the account handle between these steps
	- Add team/role management features, completely irrelevant for the sole contributor.
	- Add **zero** value to the purpose outlined in line 1.

The drawbacks are concrete and real. The benefits are irrelevant at this stage. Until this balance changes, this issue will remain in "wontfix".

**Comment by keepassium** [comment]
I see you have [a history](https://www.google.com/search?q=neustradamus+organization+site:github.com) of harassing the maintainers to convert into organizations — with no other motivation than "it's _better_, it's free, others did it". You  don't seem to mention those who refused and [asked you](https://github.com/laurent22/joplin/issues/7558) [to stop](https://github.com/webmin/webmin/issues/876) [spamming](https://github.com/hmailserver/hmailserver/issues/410). 

I don't know what your agenda is nor does it concern me. It only pains me to see how much time other maintainers wasted responding to these empty distractions. 

This issue is closed and won't be worked on. Please refrain from reopening or resubmitting it, or your account will be the first one to get banned in this project.  Thank you and farewell.
