### ISSUE TITLE
[Question] What if I use a feature which isn’t supported in the free version on my desktop?

### ISSUE THREAD

**Issue by lajawi** [keepassium/KeePassium#306]
As the title says, I want to know what happens if I use a feature which is behind a paywall in Keepassium, but isn’t on e.g. in KeePassXC on desktop?

Day for example, I setup to use a YubiKey to unlock my database on my desktop, can I then use the YubiKey in Keepassium as well, or am I then restricted from opening the database all together? How do other, database specific features work (e.g. field references)?

**Comment by keepassium** [comment]
Well, by design KeePassium does not know anything about your desktop setup: a database is just a database, regardless of where it came from. And by design, the database contains no indication whether it needs a password, a key file, a YubiKey, or some combination thereof. The app just takes your key components (whichever you provide), process them into an encryption key, and then check whether the key fits.

Premium features just won't be available/selectable/visible in the free version:
- It won't be possible to select a hardware key, so you won't be able to unlock a YubiKey-protected DB. 
- Field references would be shown as they are actually stored (`{REF:…}`), the app won't resolve them (but won't modify them, either). 
- The other premium features are not related to database content at all.

**Comment by lajawi** [comment]
> It won't be possible to select a hardware key, so you won't be able to unlock a YubiKey-protected DB.

Bummer, but understandable.

> Field references would be shown as they are actually stored (`{REF:…}`), the app won't resolve them (but won't modify them, either).

I've just tested this, and in Keepassium it shows up as `{REF:...}`, but if I try to use it (aka copy it, or use autofill), it does put in the right value (the one its referencing), so it is still useable.

**Comment by keepassium** [comment]
> I've just tested this, and in Keepassium it shows up as `{REF:...}`, but if I try to use it (aka copy it, or use autofill), it does put in the right value (the one its referencing), so it is still useable.

Now, _that_ is indeed an oversight :)

**Comment by lajawi** [comment]
> Now, _that_ is indeed an oversight :)

Whoops, I thought that was by design. Glad I could bring it to your attention!

**Comment by keepassium** [comment]
@lajawi , no worries, I'd rather build new roads than reinforce roadblocks ;)
