### ISSUE TITLE
Make it possible to change group's AutoFill and Search settings

### ISSUE THREAD

**Issue by OculiViridi** [keepassium/KeePassium#313]
### What I'd like

Add 2 options:

1. To enable/disable the inclusion of **expired entries** when making a search in the database.
2. To enable/disable the inclusion of **expired entries** when using AutoFill (and Quick AutoFill) for the database.

My suggestion is to add the options as on/off switch like this:
1. In _Settings - AutoFill settings - Include expired entries_ (new switch, default off)
2. In _Settings - Search settings - Include expired entries_ (new switch, default off)

Like discussed in my other suggestion #289, those settings maybe database specific or application wide for all databases. However, it would be more practical to put the option in one place, with the list of databases (as an on/off switch list) to which it should be applied, rather than having to select the option for each individual database on Database specific settings panel.

### Why

Sometimes, when waiting for AutoFill suggestions, I also get expired accounts as results. On KeePass XC for PC there's the option to exclude expired entries from AutoType, so my idea is to simply replicate the same behaviour.
The same applies to the option for manual search. Having the possibility to exclude expired accounts when searching it might make things cleaner for someone! 😉 

Thanks!

**Comment by keepassium** [comment]
Thank you for the suggestion! 

If we focus on the "Why" part, I believe there is already a cleaner and more ecosystem-compatible way of doing this. It is the "Search" and "Auto-Type" settings of the group. ("Auto-Type" is also available for specific entries.)
<img width="790" alt="Screenshot 2023-09-15 at 16 31 13" src="https://github.com/keepassium/KeePassium/assets/38399598/d3f43157-eed6-4631-b636-24daf348f5a5">

KeePassium respects these settings, so entries from a non-searchable group should not appear in search, and entries with Auto-Type disabled won't show up in AutoFill. (Well, at least theoretically; this was tested only superficially.) But for the moment you would need to change them using KeePassXC, because KeePassium does not expose these settings in Group Editor UI.

I will adjust the title, if you don't mind.

**Comment by keepassium** [comment]
Done in commit 7d856e3ab92fadd2dddec5d69316105bdf1f217b, released in v1.48.142
