### ISSUE TITLE
Entry icon not updated after downloading favicon

### ISSUE THREAD

**Issue by matheusgomesms** [keepassium/KeePassium#323]
Hi there!

First of all, thanks for the awesome work on KeePassium, and on the recently possibility of downloading favicons!

Not sure if this is intended, but when downloading a favicon successfully, the favicon is not used already. The downloaded favicon is stored with the other icons so the currently workflow is:

1 - click on the current icon
2 - download favicon
3 - click again on the current icon
4 - click change icon
5 - click on different icon than the one downloaded (because the one download is selected but not active)
6 - click change icon again
7 - click on the correct favicon
8 - save changes

So this is kinda of a bug and of an enhancement. In my opinion (as used by KeePassXC if I'm not mistaken), the workflow would be something as:

1 - click on the current icon
2 - download favicon
3 - the downloaded favicon is already presented
4 - save changes

Does it make sense? Thanks again for your wonderful work!

**Comment by keepassium** [comment]
Yeah, this is a bug… I have bumped into it when making screenshots for the release announcement, so it was too late :) It certainly worked during the development, though. I'll get it fixed in the next update.

In the meanwhile, if you save changes after step 2 "Download favicon", the entry will have the new icon. It's just the entry editor does not refresh the UI after downloading, but everything else should look and work as expected.
