### ISSUE TITLE
iOS, Apple Files App, OneDrive

### ISSUE THREAD

**Issue by tdtrumble** [keepassium/KeePassium#332]
**Description**

I used to access a db stored on onedrive through the Files app on my iPhone. Over the last two days I’ve been unable to access it via that method. When I browse and try to open it from within KeePassium, usually nothing happens at all, it takes me back to the databases screen as if it was going to open but the db never actually showed up on the screen or asks me for my authentication info. Sometimes when I attempt it I get a message stating the provider is not responding.

Only mentioning in case there is some bigger issue with the Files app, I can still access my db by connecting directly to onedrive from keepassium.

**How to reproduce**
1. Go to Databases screen
2. Tap on +, open database
3. Browse to a Keepass db on onedrive via iOS files, select it

**Expected behavior**
Opens db, asks for password

**Environment:**
 - Device: iPhone 13
 - OS: 17.1.2
 - App Version: 1.48.142

**Comment by keepassium** [comment]
> Sometimes when I attempt it I get a message stating the provider is not responding.

This means that OneDrive did not respond to KeePassium's request within 10 seconds. This can be an issue within OneDrive itself, or indeed a bigger issue at the system level (see #109). In either case, not KeePassium's bug. This is just how file access works since iOS 13; and this was one of the reasons for the in-app OneDrive support.

Your best bet is to restart the device…
