### ISSUE TITLE
iOS Dropbox Sync not working

### ISSUE THREAD

**Issue by sahokun** [keepassium/KeePassium#340]
**Description**
Referring to kdbx in Dropbox.
Previously, after the DB was updated in Dropbox, sliding down and Reloading in KeePassium DB List would update the DB.
However, now it is not updated and the DB must be referenced anew.
On the Dropbox app it is updated.

**How to reproduce**
1. (PC) Place kdbx on Dropbox.
2. (iOS) Open kdbx on Dropbox in the DB list of KeePassium and register it in KeePassium.
3. (PC)Modify kdbx using KeePassXC or other software.
4. (iOS) Slide down in the DB list of KeePassium.
-> It will not reload to the latest version.

**Expected behavior**
Display the latest DB updated in Dropbox on KeePassium.

**Environment:**
 - Device: MacOS/iPhone
 - OS: iOS17.2.1
 - App Version: KeePassium 1.48/Dropbox 362.7(2024/2/7release)

**Additional context**
I noticed this today. I think it was updated correctly a month ago for example.

**Comment by keepassium** [comment]
Email reports about this issue started around November-December. A bit earlier, Dropbox changed how it integrates with the Files app. I learned about the change from the new button in Dropbox settings, titled "[Convert all to classic integration](https://www.dropboxforum.com/t5/Apps-and-Installations/iOS-app-quot-Convert-all-to-classic-integration-quot/m-p/742129)".

To people reaching out via email, I suggested to roll back to classic integration as a test. About five people confirmed this solved the issue. One confirmed that the issue remained. 

So try Dropbox → Account → tap the gear icon in top-right corner → Native Files.app integration → tap "Convert all to classic integration". If this helps, please comment in the related [Dropbox thread](https://www.dropboxforum.com/t5/Apps-and-Installations/iOS-app-quot-Convert-all-to-classic-integration-quot/m-p/742129), because Dropbox seems to believe their new integration is "significantly more reliable"…

**Comment by sahokun** [comment]
I appreciate your response, it is very much appreciated.
I have improved by making it classic. (Although there seems to be a time lag of about a minute between checking for updates on the Dropbox App and being able to detect the latest version in KeePassium)
I am concerned about the future of the integration with Dropbox in the future, but for now the problem is solved.

**Comment by keepassium** [comment]
> I am concerned about the future of the integration with Dropbox in the future

Me too. So I plan to add a direct connection to Dropbox as an alternative sync option. This way, if Dropbox' integration with Files misbehaves further, you would have possibility to connect directly from KeePassium, avoiding the integration problems. This approach was [introduced](https://keepassium.com/blog/2022/12/keepassium-1.38/#in-app-onedrive) a year ago for OneDrive and proved to be a lifesaver.

**Comment by DannieBGoode** [comment]
thanks for this, is there an ETA for the Dropbox WebDav integration?

**Comment by keepassium** [comment]
> thanks for this, is there an ETA for the Dropbox WebDav integration?

Nothing I can share, unfortunately. Just had rather stressful two months after promising something done in two weeks :)

But as long as switching back to classic integration fixes Dropbox sync, I don't think the direct connection is too urgent.

**Comment by keepassium** [comment]
@DannieBGoode , direct Dropbox connection is scheduled for v1.52. So ETA is April :)
