### ISSUE TITLE
iOS: password-to-clipboard function changes uppercase letters to lowercase

### ISSUE THREAD

**Issue by codingexamples** [keepassium/KeePassium#345]
**Description**
When I use the "1-click" password-to-clipboard function of the iOS app, the password is copied to the clipboard as expected. BUT: some (NOT all!) of the uppercase letters are *sometimes* changed to lowercase letters in the clipboard. Just to clarify: The password itsself in the database stays unchanged. But the copied result in the clipboard has some of its letters changed from uppercase to lowercase.

The displayed password is correct. Additionally: manually selecting the password-text in the app and then using the iOS-"copy" function works perfectly fine.

**How to reproduce**
I did not find a way to reproduce the behaviour in a repeatable pattern. 

**Expected behavior**
The password in the clipboard shall be identical with the password in the database (and the password displayed).

**Environment:**
 - Device: iPhone 15 Pro
 - OS: iOS17.3.1
 - App Version: 1.48.142

**Comment by keepassium** [comment]
This is a system bug that happens when copied text contains a `:` (colon) symbol. It can be reproduced outside/without KeePassium. 

I have reported it to Apple back in 2020, no resolution so far. Here's a public copy of the report: https://openradar.appspot.com/FB8263927

Feel free to [report it to Apple](https://feedbackassistant.apple.com) too, quoting "FB8263927" as a related report.
