### ISSUE TITLE
TOTP autofill?

### ISSUE THREAD

**Issue by k1zn** [keepassium/KeePassium#361]
**Describe the feature you'd like**
Hi! It would be cool if the app could automatically insert a 2FA code into the input field. If this is not possible for some reason, or already exists, I apologize.

**Comment by keepassium** [comment]
Inserting automatically is not possible, because Apple does not provide access for that.

As a workaround, though, KeePassium AutoFill copies the OTP to clipboard. So you can auto-fill the username and password, and then manually paste the 2FA code to the appropriate field. Not ideal, but faster than switching between apps.

**Comment by k1zn** [comment]
Thank you for the quick response!
