### ISSUE TITLE
iOS Autofilling memory insufficient workaround

### ISSUE THREAD

**Issue by teddyhoss** [keepassium/KeePassium#372]
While using the Autofilling feature, you receive a message saying that there is insufficient memory. I read a thread that would be about how KeePassium handles icons. Many people like me have databases with many icons (added by KeePassXC), so a button (in the settings section) to delete all the icons or resize them would be a useful workaround for many to reuse the "lost" function without having to manually modify thousands of entries.

**Comment by keepassium** [comment]
The issue with custom icons (#354) affected only icons added by KeePassium, and has already been fixed. So there is no need for workarounds to resize the icons. Deletion is already possible, one-by-one, both in KeePassium and KeePassXC.

> While using the Autofilling feature, you receive a message saying that there is insufficient memory.

That message is caused by [iOS memory limits for AutoFill](https://keepassium.com/articles/autofill-memory-limits/). This is not a bug, it is just objective reality that hits larger databases. Possible reasons and workarounds are already well documented.
