### ISSUE TITLE
An entry that behaves as a shortcut to open a database

### ISSUE THREAD

**Issue by latvia234** [keepassium/KeePassium#380]
As a business user I have access to multiple kdbx databases. 

It is impossible to remember the password of every database. I do not like to use convenience unlock because it is not always safe.

An entry that behaves as a shortcut to open another database could be a solution.

It should be a special entry containing the password and name of another database, and it should behave as a shortcut.

When you click on the entry it will open another database. Really simple.

It would be helpful if the user could create multiple database shortcut entries in a database.

Right now my team cannot use Keepassium because this feature or something similar is not available.

I hope that one day a feature like this can be implemented in Keepassium.

**Comment by keepassium** [comment]
Something like this? ;)

<img width="375" alt="Screenshot of the upcoming 'linked database' feature" src="https://github.com/user-attachments/assets/1260df3f-b9bf-485c-b689-58ffc0302514">


This is already implemented and awaits its turn for the next update. But technically the feature was first requested in #202, so I would close this as a duplicate.

**Comment by latvia234** [comment]
Thanks for creating this new feature. 🙂

Yes, I remember that a similar feature was requested already.

This would work for me, however I have one question.

When you are in the main database overview you could see folders and normal entries.

When you click or tab on a linked database entry, I would prefer it behaves like a folder. After the tab or click it should open the database instantly.

When you want to edit the entry, you can do this via a long tab, the same as editing a folder. Maybe this is already possible...

**Comment by keepassium** [comment]
Thanks for the feedback!

Opening a linked database as a group would be awesome, and might be possible in the future, but there are two challenges.

Technical challenge: memory pressure. An opened database takes memory, mainly because of attached files. Saving a database takes even more memory to compute the encryption key (Argon2 being a memory-hard function). On an iPhone, if you dive a couple DBs deep and try to edit a "sub-sub-database" — there is a good chance of running out of memory. 

This is why KeePassium tries to keep only one DB open unless absolutely necessary. The only exception for now is when moving groups/entries to another DB. For now, opening a linked database means switching to another file, rather than opening a "subdatabase".

Usability: tapping an entry and immediately ending up in another database would violate the principle of least surprise. So there _has_ to be an intermediate step. Plus, quite a few people don't know the swipe and long-press gestures (that's why there are various `⋮` and `⋯` buttons in lists).

In principle, both problems are solvable. The question is whether they are worth solving :) Let's wait for wider feedback on linked databases and see how it goes.

**Comment by latvia234** [comment]
Thanks for the explanation :)

> Usability: tapping an entry and immediately ending up in another database would violate the principle of least surprise. So there has to be an intermediate step. Plus, quite a few people don't know the swipe and long-press gestures (that's why there are various ⋮ and ⋯ buttons in lists).

Maybe you can add an icon that makes the user aware of a linked database entry. If they see the icon they expect to open another database.

I would prefer to tab or click only once to open a linked database entry instead of twice. If you've made it yourself it does not surprise me that it will open another database. If you share it with other users they know that it will open another database if they see the icon and the name of the entry. They don't need another window to remember that they open a new database.

Anyway, I'm happy that this feature will be available. Thanks for creating Keepassium.

I'm curious about feedback of other users.

**Comment by keepassium** [comment]
Done in 1.53.154 (now in beta) via b6df88422e1ba3e05d52601b86f70a744caa552c
