### ISSUE TITLE
MacOS: Edit dialog very small

### ISSUE THREAD

**Issue by Fischmuetze** [keepassium/KeePassium#390]
Would it be possible by any chance to make the editing window significantly larger in relation to the main window?

The edit dialog is really very small and really extremely impractical for larger comment content - small as a postage stamp ;) ... 

Imho ist should have the width and height of 80-90% of the item details pane - see the screenshot 

Thank you!!!

![keepassium](https://github.com/user-attachments/assets/8ce97b7c-170f-4ffc-980b-ac817f82e10f)

**Comment by keepassium** [comment]
This is a standard size of a "form for editing stuff". It can probably be stretched, but I'm not sure what good this would do: the fields are already quite long, and vertical space is limited anyway.

From the screenshot, it seems you are more interested in secure notes rather than password management, right? If so, maybe we can add a way to maximize the Notes field to cover most of the dialog window. Would this work for you?

**Comment by keepassium** [comment]
Closing as stale. Feel free to comment and reopen discussion.
