### ISSUE TITLE
Slight discrepancies in UI between Autofill and Standalone

### ISSUE THREAD

**Issue by magebarf** [keepassium/KeePassium#4]
Calling this an issue might be a stretch, but I don't know any better way to report minor nitpicks. :)

Deployed Beta 23 today, and encountered a few "upgrade related" (just an assumption, will see if they happen again in some context) error message, both in App mode and Autofill mode.

I then noticed that the way the error messages are presented differs slightly in Autofill and in standalone versions of the UI.

It may be by design, or it may be a work in progress not fully deployed across the code base, or simply not even something that's been reflected upon. It won't cause any problems for any users, but possibly reduce the "uniformity" of the UX. Attaching images of the two variants.

Standalone:
![standalone](https://user-images.githubusercontent.com/3879511/58987713-634e2300-87e0-11e9-9f09-64d18534a537.png)

Autofill:
![autofill](https://user-images.githubusercontent.com/3879511/58987714-63e6b980-87e0-11e9-92b5-e425c83c95af.png)

**Comment by keepassium** [comment]
The errors mean that the system has warned KeePassium that there is little memory (RAM) left. Normally, this should happen when you open a heavy database, but apparently also happens in normal use. I will need to take this into account and handle these cases differently.

As for the uniformity, you are absolutely right and this is my pain point. AutoFill is basically a separate app with its own UI components. I have started refactoring the main app and unifying the UI components. This has proven to take way more time than I expected, so I had to pause refactoring and focus on AppStore release as the main priority. Some day, the unification will be done...

**Comment by nijhawank** [comment]
Hello Andrei,

I also saw this error message (not enough memory) just yesterday and within a single day of installing it on my wife's phone. However I had never seen this message on my phone during my couple weeks of usage and we both have the same models so no difference in RAM.

Whats more important is that the error message appeared just after opening KeePassium and before I even attempted the database unlock similar to what the first screenshot shows. So this is nothing about database being huge or key derivation settings because we haven't attempted a database unlock yet.

Thoughts?

**Comment by magebarf** [comment]
As for me seeing it, I kind of wrote it down to being due to me trying to cause the issue, by reproducing the previous bug (#1 ) the last time before upgrading, and something odd with that flag being propagated during the upgrade.

So far haven't encountered the error message any more on my end, but will keep my eyes open.

**Comment by keepassium** [comment]
Memory shortage is a system-wide condition, that can be caused by another app that needs a lot of memory. In this case, the system sends "memory warnings" to all apps, asking them to free some memory if they can (clear some caches, for example).

Unfortunately, when I implemented processing of memory warnings, I assumed they would happen only when *my* app takes up too much memory (e.g. choking on too ambitious Argon2 settings). I will look into this and get rid of redundant error messages (and check for memory leaks, of course :)

Thanks for reporting!

**Comment by magebarf** [comment]
Been there, done that... Those low memory methods and delegates always gets invoked when you expect it the least. :)
