### ISSUE TITLE
Minor bug “File Sorting” settings

### ISSUE THREAD

**Issue by raymond127** [keepassium/KeePassium#51]
**Describe Bug:**
Then I click on „file sorting“ settings there is no title/caption and „Done“ Button visible.
This happens only on my iPad (Userinformation below), not on my personal iPhone 6s (same OS and App Version like the iPad). 

![08C46726-6012-4B49-9A28-AC98C8834E39](https://user-images.githubusercontent.com/54579879/63773225-0774d100-c8db-11e9-9123-29000b0828dc.jpeg)

**Steps to reproduce the behavior:**
1. Open KeePassium on the iPad 10.5.
2. Click on ‘file sorting’ settings.
3. See no caption/title and no „Done“ Button.

 

**Expected behavior:**
Caption/title and “Done” Button is visible.

 
**User Information:**
 - Device: iPad Pro 10.5
 - OS: iOS 12.4.1
 - App Version: 1.01.32

**Comment by keepassium** [comment]
This was an intentional design decision. Although it is quite difficult to explain now...

- I struggled to find a good title for this popover. "File Sorting" is too generic and not quite accurate, because "Show Backup Files" is not about sorting. Since the popover is very simple, I thought it would be better to let the content explain itself, rather than distract the user with a generic title.
- The "Done" button would be redundant here. This is a quick one-tap action page. When you change one of the options, the changes are applied (and shown) immediately and the popover closes. Tapping anywhere also on the screen would also close the popover. The "Done" button would only distract the user without any good cause.

Now, the Settings popover (just the next button) is a completely different story: it has both a title and a "Done" button. Here's why:

- In contrast to File Sorting, App Settings is a complicated page with several sections. A familiar one-word title helps to quickly understand what this all is about.
- The "Done" button is admittedly redundant: all the changes are applied immediately, just like with File Sorting. However, the user cannot immediately see the effect of their changes. So while technically this button simply closes the popover, psychologically it reassures the user that their changes are indeed saved and applied.

None of these considerations apply on the iPhone. According to Apple's [guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/views/popovers/), all the popovers have to displayed in full screen. The buttons become necessary to be able to close the popover. And with the buttons comes a title bar...

Do you think it would be useful to show a File Sorting title on the iPad as well?

**Comment by raymond127** [comment]
Thanks for your detailed and plausible answer.

You put a lot thought into this and I understand your struggle. In my opinion it would look nice, because of consistency. 

But you got my support anyway.
I am sorry that I recognized this as a bug.

**Comment by keepassium** [comment]
No problem, it does look like a bug :) And since you noticed this, the inconsistency must be more evident than I thought. I will add a title to make it more coherent. Thanks for reporting!
