### ISSUE TITLE
Use multiple Databases without Premium

### ISSUE THREAD

**Issue by raymond127** [keepassium/KeePassium#52]
**Describe the bug**
It is possible to use multiple database without Premium. Just add a new database in the KeePassium folder, not in the app itself.

**To Reproduce**
1. Open the File Manager
2. Go to the KeePassium folder
3. Copy the existing Database and paste it in the KeePassium folder (or transfer one from your computer)
4. Open KeePassium and refresh the Database list
5. Open the copied Database. Delete all entries and change the Master Password.
6. Now you have two Databases, which can be used at the same time. Also the Master Password can be remembered for both databases.

**Expected behavior**
A window with a reference to the Premium feature (after step 4) 
**or**
it should not be possible to store both Master Passwords at the same time.

**User Information (please complete the following information):**
 - Device: iPhone 6s
 - OS: iOS 12.4.1
 - App Version: 1.01.32

**Additional context**
I wanted to buy the premium version and read the premium features. Than I noticed that I used two Databases (copied from my computer) all the time without knowing that is a premium feature.

Perhaps you know about that, but I thought that is in your interest :)

**Comment by keepassium** [comment]
Yep :) 

At the moment, the divider between the free and premium tiers is more of a red tape barrier rather than a brick wall. There are a couple of loopholes. Some of them ensure that the users who cancelled their premium can still access all their databases. Others are technically complicated to fix.

The main reason, however, is that strengthening the fence is not worth the effort and would not make the app any better for the users.

- Those who want to support the app would upgrade to premium anyway.
- Those who don't want or cannot — they would stick to the free version.
- A small percentage of free-tier users would find a loophole, use it and feel good :) If the loophole was patched, they would still stick to the free tier. Only a small fraction of them would (reluctantly) pay for premium.

I think it makes more sense to increase the number of those who are happy to upgrade, rather than twist arms of those who never would. So, as long as this bug is not abused by thousands of people, I don't think it is worth fixing.

Thanks for reporting, though!

**Comment by raymond127** [comment]
Thanks for the answer. I like your attitude. You really thought this through.
