### ISSUE TITLE
Background sync does not work

### ISSUE THREAD

**Issue by dai640** [keepassium/KeePassium#55]
Keepassium When adding a database through the system's "file", the source is a third-party cloud, I found that the Keepassium does not automatically synchronize, sometimes it will not automatically synchronize for a few days, when you manually pull down the refresh, it will not automatically synchronize ，Only when you perform an open database through the top right corner, through the system's "file", the fact is that you do not need to add it again, just need to open this step, and then exit, the database will synchronize the latest data。

**Comment by keepassium** [comment]
Synchronization is completely managed by the third-party apps, and ultimately depends on their bugs. This is both the benefit and the curse of the chosen sync approach...

Can you please specify:
- which third-party cloud is involved (Nextcloud, by any chance?)
- what iOS version do you use?

**Comment by dai640** [comment]
1. webdav，from: jianguoyun.com 
   dropbox

2.iOS 12.4

**Comment by keepassium** [comment]
It seems the storage provider apps perform synchronization only when they are on the screen (in foreground).

The usual suspect would be the background refresh (device Settings — General — Background App Refresh). Please check the settings and make sure that both Dropbox and Nustore are allowed to refresh in background. It might be also useful to double-check each app for similar settings.

**Comment by dai640** [comment]
I confirmed them both Dropbox and Nustore are allowed to refresh in background，Because I can see their real-time refresh on the app and synchronize the latest data, but the Keepassium can't realize automatic synchronization. The pull-down refresh is also invalid. It is necessary to add the path to the system "file" and then exit. The latest data can be synchronized. This will make the data that I update on my PC not automatically sync.

**Comment by keepassium** [comment]
I guess I'm missing something...

> I can see their real-time refresh on the app

When you see the files refresh in real time in their original iOS apps, that means these apps are on screen (in foreground). And the issue is related to background sync, when the storage apps are not running.

One possibility to check this would be to test with another app (for example, Apple's Pages or Numbers). Create a Numbers spreadsheet on your phone, save it to Nutstore, check if the file appears on desktop. Then edit the file on desktop and open Numbers on the phone (without using the iOS Files app). Does the sync work in this scenario?

**Comment by dai640** [comment]
I tested the synchronization speed of the strongbox, using the same database, also the webdav way of Nustore to synchronize, edit and modify the database file on the PC and save it, then open strongbox, keepassium on the phone, and find the background synchronization speed of strongbox. Soon, almost open the app is already synchronized, keepassium can not be synchronized, the same way, the same database, so you can judge this is definitely not an iOS problem.

 And I used the premise of the database timeout problem, [#34 ](https://github.com/keepassium/KeePassium/issues/34) strongbox is doing very well, you can use fingerprints instead of the troublesome keyboard to enter the master password.

**Comment by keepassium** [comment]
Thanks for the update.

> I tested the synchronization speed of the strongbox, using the same database, also the webdav way of Nustore to synchronize

Strongbox has built-in support for WebDAV. Did you use that option, or added the database via Files?

> And I used the premise of the database timeout problem, #34 strongbox is doing very well, I can use fingerprints instead of the troublesome keyboard to enter the master password.

My time is limited, so I have to prioritise KeePassium development. Most frequently requested features have higher priority. As for #34, it is not a trivial 5-minute task and so far it has been requested by one person only. So it's not very high in the priority list... Thank you for understanding.

**Comment by dai640** [comment]
> Strongbox has built-in support for WebDAV. Did you use that option, or added the database via Files?

I use it directly through its built-in WebDAV option. I think that as a password management software, if the synchronization efficiency is not high, it will cause trouble in multi-end synchronization, because manual refresh can not be solved, let alone automatic synchronization in the background.  .


> My time is limited, so I have to prioritise KeePassium development. Most frequently requested features have higher priority. As for #34, it is not a trivial 5-minute task and so far it has been requested by one person only. So it's not very high in the priority list... Thank you for understanding.

I understand that you as a developer often have limited time.  Because I like this app, I started using the beta version, so I hope it can do better.

Of course, if you can solve this problem perfectly, it is best because the keyboard is used to manually input complex passwords, and the passwords may be wrong and inefficient.  As far as I know, the current similar password management APP supports the use of biometric unlocking instead of keyboard.

**Comment by dai640** [comment]
Finally, thank you for your efforts and developed this APP. I always like it very much.

**Comment by dai640** [comment]
I saw the official documentation of the Keepassium on the website. This webdav is fully supported.
![2019-09-14_133428](https://user-images.githubusercontent.com/8486208/64904072-ce1fcc00-d6f6-11e9-8cac-f6a608484cdc.jpg)

**Comment by keepassium** [comment]
> the same way, the same database, so you can judge this is definitely not an iOS problem.

> I use it directly through its built-in WebDAV option. 

This is not "the same way". 

On one hand, you tested Strongbox' built-in WebDAV sync: the app itself directly connects to the server and downloads the data.

On the other hand, you tested KeePassium, which delegates all synchronization to the Nutstore app. (KeePassium asks Nutstore to provide the latest data, and uses whatever is returned by Nutstore.)

KeePassium's sync is completely defined by the third-party app it uses. If the storage app fails to sync in background (a common issue with NextCloud app), I cannot do anything about it. I would suggest you to check with Nutstore support or user-reported problems with background sync.

> I saw the official documentation of the Keepassium on the website. This webdav is fully supported.

WebDAV is listed as "full support with a third-party app", and that app is not Nutstore. Once I receive more feedback about Nutstore, I will be happy to include it in the list (either as supported or not).

**Comment by dai640** [comment]
Sorry, as far as I know, since webdav is a standard protocol, according to your explanation, although webdav is supported, it depends on the service provider of each different webdav. I can't understand this at all. Does this cause misunderstandings and contradictions? Or you can directly build webdav function in keepassium, just like strongbox, according to your official documentation, "full support with a third-party app" maybe not cause misunderstanding, right?

**Comment by keepassium** [comment]
> since webdav is a standard protocol, according to your explanation, although webdav is supported, it depends on the service provider of each different webdav.

It depends on the service provider's client app that connects to the service provider's servers. Imagine opening the same webpage in different web browsers: latest Chrome vs Internet Explorer 6. The protocol is standard, the server and the page are the same, but you will likely have very different experience with these browsers. Some apps are just more thoroughly implemented, tested and refined than others.

> keepassium does not have a built-in sdk interface, it is added from the "file" app, then iOS Install these app calls

I'm not sure I completely understood what you mean, but in general — yes, KeePassium does not connect to any servers directly, and relies on storage providers' apps for that. If these apps don't support background sync, KeePassium cannot do anything about that.

**Comment by dai640** [comment]
I think it may be that I understand it wrong. What do you mean by "If these apps don't support background sync" are these google drives, onedrive, dropbox, etc? I synced a file on the PC to these third-party clouds, and I can sync these files to the phone immediately. Isn't this the background sync? Isn't it possible to say that these applications are ok, can they be synchronized in the background? According to what you mean, how do these applications support background synchronization?

**Comment by keepassium** [comment]
The full sync chain looks like this:

`KeePassXC (desktop) ↔︎ Provider's desktop app ↔︎ Provider's servers ↔︎ Provider's iOS app ↔︎ KeePassium`

The sync issue you are experiencing is most likely caused by the "Provider's iOS app" part (Nutstore for iOS, Dropbox for iOS, etc). That app is responsible for detecting changes on the server and downloading the latest copy of the database. 

When you open the provider's iOS app, it runs in foreground (on screen), and works just fine: you can see that files modified on desktop are immediately changed in the iOS app of the storage provider.`

When you open KeePassium, the provider's app has to run synchronization in a background process (off the screen). Apparently, this is not so easy to implement correctly: some provider's apps do that very well (iCloud Drive, Dropbox, OneDrive, GDrive), others not so much (Nextcloud). 

I don't know anything about Nutstore's iOS app, but Dropbox works just fine in background for most iOS users. Therefore I tend to think that Dropbox sync issue is likely caused by your system settings, rather than by KeePassium's implementaion. There was a similar issue reported a few months ago (background sync did not work with Dropbox). We found that was caused by the disabled "Background App Refresh" option, as I already [mentioned](https://github.com/keepassium/KeePassium/issues/55#issuecomment-529881007). 

If this starts to happen to many people, I will be happy to reopen the issue. In the meanwhile, I would suggest you to double-check your Dropbox/Nutstore settings and maybe search forums for similar issues in Nutstore for iOS.
