### ISSUE TITLE
iPadOS 13.1 - Stuck in the launch screen with a logo

### ISSUE THREAD

**Issue by keepassium** [keepassium/KeePassium#66]
**Describe the bug**
When launched on an iPad with iOS 13.1 (release version), KeePassium shows a white screen with a logo — and that's it.

**To Reproduce**
1. Upgrade to iOS 13.1
2. Launch KeePassium
3. Observe the white screen with a logo

**Screenshots**

![Simulator Screen Shot - iPad Pro (12 9-inch) (3rd generation) - 2019-09-25 at 20 44 57](https://user-images.githubusercontent.com/38399598/65632192-62ccd880-dfd9-11e9-88c3-d267c525de01.png)

**User Information (please complete the following information):**
 - Device: iPad (simulator or device), 
 - OS: iOS 13.1 (release)
 - App Version: 1.02.36, 1.03.37

**Workaround**
Rotating the screen resolves the issue, at least on simulator.

**Comment by magebarf** [comment]
Reproducible also on iPhone XR running iOS 13.1, in App version 1.03.37.

Reproduction description was slightly different, as I was using app launcher to switch from home screen to App, rather than start it from the home screen icon.
Also was in dark mode, so screen is not necessarily white.

A gut feeling, which I haven't yet been able to verify fully as it's only happened once, is that it was waiting for the Face ID prompt.

**Comment by keepassium** [comment]
I've found the culprit on StackOverflow: [UISplitViewController will not correctly collapse at launch on iPad iOS 13](https://stackoverflow.com/questions/57699571/uisplitviewcontroller-will-not-correctly-collapse-at-launch-on-ipad-ios-13). 

It seems, the solution will be the same as #60: wait for the next release of Xcode...
