### ISSUE TITLE
Cannot select *.kdbx file from Nextcloud

### ISSUE THREAD

**Issue by pcace** [keepassium/KeePassium#73]
Hi,

i have a strange behaviour here with a new install of keepassium from appstore: 
when i open keepassium the first time, select open existing database, then navigate to the folder containing my kdbx file, i just cannot select it. 
If i open the files app, navigate to my kdbx file, it has the kepassium icon and i can click it. When keepassium then opens, i just get to the "create new database or select existing...." screen. 

Is this a bug? or am i stupid?

EDIT: i am on iOS 13.1.2 on an iPhone SE and the same happens on iPad 2018 13.1.x

**Comment by keepassium** [comment]
This can happen if you have another (recent) KeePass app installed.

The reason is, each app declares to the system that it is *the* app responsible for .kdbx files. So, for the system the database is not just a file with a certain extension, but "a MiniKeePass document", "a KyPass document", and so on. So KeePassium has to [explicitly declare](https://github.com/keepassium/KeePassium/blob/master/KeePassium/Info.plist#L21) that it can open "MiniKeePass documents", "KyPass documents", etc. Some of the newer apps (such as AuthPass or MiKee) are not yet included in the declaration, and the system thinks that KeePassium cannot open their files. Therefore, they are greyed out in the file selection dialog.

One solution is to open the iOS Files app — long-press the database — Share — scroll right the icons — More — Open in KeePassium. This should add the database to KeePassium (but not AutoFill). Alternatively, you can uninstall the other app(s), and the database should become available for selection in KeePassium. Then reinstall the other apps.

(By the way, Nextcloud integration with the Files is currently [broken](https://github.com/nextcloud/ios/issues/941) on iOS 13. And there are a couple of other [known issues](https://keepassium.com/articles/sync-ios-keepass-with-nextcloud/), make sure you are aware of them.)

**Comment by keepassium** [comment]
@pcace, did it work out?

**Comment by pcace** [comment]
Hey, it took me a while, but there is kind of a fix for that: 

https://github.com/nextcloud/ios/issues/951#issuecomment-551101147

cheers and good luck!

**Comment by keepassium** [comment]
@pcace, thanks for the update!

I guess we can consider this resolved, then :)
