### ISSUE TITLE
Feature request: Auto select credentials when there is just one entry

### ISSUE THREAD

**Issue by igorkulman** [keepassium/KeePassium#76]
**Describe a feature you'd like**
Using the auto fill extension when I try to login to an website the extension opens and shows me all the entries (logins) for that website to choose from.

When there is just 1 entry I would like it to be "tapped" automatically, so I do not have to do it manually. 

The flow should be the extension opening, face id / touch id auth, closing with the credentials being filled in without having to choose the 1 matching entry.

**Comment by keepassium** [comment]
Thanks, Igor, this is a great idea! (And quite easy to do :)

My only concern is that AutoFill search is not that perfect... The single found entry might still be the wrong one — but the user won't be able to switch to manual search. 

If you have an idea how to address this, I would appreciate it. Otherwise, I'll just implement this anyway :)

**Comment by keepassium** [comment]
Just published it in the AppStore (as v1.08.48).

**Comment by shadow1runner** [comment]
Sorry to jump in on this, but am I the only one for whom this feature doesn’t seem to work? My flow is as follows:

* Navigate to a web page, e.g. ` https://www.airbnb.com/`; click on auto fill
* Picker appears with only a single search result, but no auto-select happens; looking at the code I guess that’s due to ` hasPerfectMatch` evaluating to `false`.

I’ve cross-checked and the URL in the DB is identical to the Safari URL. Might I be facing an issue where this one and only search result is still considered a `partialMatch`?

Anyway, thanks a lot for the hard work, it’s a great app!

**Comment by keepassium** [comment]
@shadow1runner, is the single search result listed under "Related entries" by any chance?

**Comment by shadow1runner** [comment]
@keepassium thank you for the quick response, and yes, it is listed under related entries. Is there a way I can improve my data keeping such that the feature works?

**Comment by keepassium** [comment]
Currently, a perfect match is when the entry and the webpage have exactly the same URL. For best result, you can set the entry's URL field to the login page (such as `https://www.airbnb.com/login`).

Unfortunately, sometimes this won't work. For example, when I first tried to select the room/dates on AirBnB, the login page URL was 

    https://www.airbnb.com/rooms/123456?location=...&source_impression_id=...&check_in=...&check_out=...&guests=...&adults=...#signup_login

Obviously, the URL will be different every time, and would not match the entry's URL value. For such cases, KeePassium uses a heuristic [similarity estimation](https://github.com/keepassium/KeePassium/blob/master/KeePassium%20AutoFill/util/SearchHelper%2Bextensions.swift#L146). Since both URL have the same host (`www.airbnb.com`), they are considered to be 70% similar (the number was selected arbitrary, to be honest). This way, however, the  entry can still be listed under "Related entries".

I'm not sure how to improve this further without creating site-specific rules...

**Comment by shadow1runner** [comment]
You’re right, it’s working fine when the URLs match 1:1 (luckily a trailing / is ignored though ;-)). So yes, this feature works under this circumstances.
Unfortunately SPAs and mobile pages tend to break this match as outlined, e.g. I’ve got a Dropbox entry with URL https://www.dropbox.com/login - navigating to it redirects to https://www.dropbox.com/m/login (unless I request desktop site, that is).

> I'm not sure how to improve this further without creating site-specific rules...

And that’s how KeepassHttp and ChromelPass handles it then, I guess. Do you happen to know how KeeFox does it? 

But they all have the advantage of being in a Desktop environment, where it’s easy to choose a different entry, while the first one is auto-selected - sth that’s not easy to do on iOS, unless #50 becomes real.
The only real alternative that comes to my mind would be to auto-select the first entry, independent of it’s an exact match or a related entry. However, I’m afraid that this breaks some use cases, especially since I can’t ever select an alternative entry this way (except maybe an additional user flag gets exposed, but this might lead to more confusion and a more crowded UX).

Anyway, the feature is working and the single additional click doesn’t hurt, thanks for the additional information.

All the best for the upcoming New Year and thanks for your support!

**Comment by keepassium** [comment]
> I’ve got a Dropbox entry with URL https://www.dropbox.com/login - navigating to it redirects to https://www.dropbox.com/m/login (unless I request desktop site, that is).

If there are only a couple of alternative URLs, you can add them as custom fields—they are also [searched](https://github.com/keepassium/KeePassium/blob/master/KeePassium%20AutoFill/util/SearchHelper%2Bextensions.swift#L208) for matching URLs.

> However, I’m afraid that this breaks some use cases, especially since I can’t ever select an alternative entry this way (except maybe an additional user flag gets exposed, but this might lead to more confusion and a more crowded UX).

Well, technically you can select an alternative entry: the auto-select triggers about 0.5~s after the search results appear. If you tap the dialog during this interval, the auto-select will be cancelled. However, in most cases the user will surely miss the first time and will have to go trough the full AutoFill cycle again (still risking to miss the 0.5~s cancellation opportunity). I thought that the extra tap required for non-perfect matches would be far less annoying :)

> And that’s how KeepassHttp and ChromelPass handles it then, I guess. Do you happen to know how KeeFox does it?

I took a quick look, but could not find how KeeFox does that. In general, a small set of site-specific rules is feasible and would probably solve the issue for most popular websites. But for now I have to focus on more pressing issues :)

**Comment by Thuranium** [comment]
Just testet this feature in Version 1.11. It is great and saves a tap, thanks a lot 👍!

Unfortunately, the URL-match _really_ has to be exact. In my scenario it did not work until I added  the trailing slash "/" at the end. 
Regarding the trailing slash I am not sure if this is a bug or a feature that it is included in the match comparison?
Did you think about using just the base domain as a match-candidate? Or you could add an option which match strategy to use for auto-fill (e.g. exact, base domain, host+port, starts with). I got this idea from Bitwarden [(match detection options)](https://help.bitwarden.com/article/uri-match-detection/) - they have these options on a per-URI basis, but I guess this is not possible with the KeePass database format.

**Comment by keepassium** [comment]
> Unfortunately, the URL-match really has to be exact. 

Yes, unfortunately this is the case at the moment. 

The main reason is that the user has only 0.6 s to cancel auto-insertion (a longer delay proved to be annoying). If AutoFill automatically selects a wrong entry, the user won't have enough time to cancel this auto-insertion. They will end up with wrong data in the login form and might not even notice this. As a result — "wrong username/password", stress, frustration...

So currently auto-select works only on perfectly matching URLs in order to avoid false positives.

> Regarding the trailing slash I am not sure if this is a bug or a feature that it is included in the match comparison?

The missing slash likely made the URLs only 98% similar, while auto-insert threshold is exactly 100%. I don't mind reducing the  threshold, the question is how low it can be. And how to offer the user an quick UI to cancel auto-insertion...

> Or you could add an option which match strategy to use for auto-fill (e.g. exact, base domain, host+port, starts with). I got this idea from Bitwarden (match detection options) - they have these options on a per-URI basis, but I guess this is not possible with the KeePass database format.

Well, technically this is possible — there are fields for hidden data. But this would be an ad-hoc solution only for KeePassium. Also, this would complicate the UI quite a bit.

> Did you think about using just the base domain as a match-candidate? 

Yes, I did. I don't remember the full thought process anymore, but the path component was also deemed important. In particular, for sorting search results by relevance. (E.g. for this repository, the entry with URL "github.com/keepassium" should be listed before other GitHub-related entries.)

But now that you've asked... Auto-insert does not require fine-tuned ranking by relevance. So maybe if there is only one search result, it makes sense to compare the base domains and initiate auto-selection even if the match is not perfect.

Of course, the challenge of an easily-cancellable UI remains, but I will think about it. Thank you for the suggestion!
