### ISSUE TITLE
Cannot add database from OneDrive - option is missing in the Locations

### ISSUE THREAD

**Issue by 0anton** [keepassium/KeePassium#80]
I read in the documentation that OneDrive is supported as a cloud sync option over Files app. However, when I try to add database file in KeePassium I don't see OneDrive in Locations.

![ScreenShot671bis](https://user-images.githubusercontent.com/17309924/69906724-2302e280-13c8-11ea-8198-a44e7ca9711d.jpg)

When I open Files app directly OneDrive option IS in Locations. In other applications, e.g. Photos when I select "Save to Files" I also able to see OneDrive:

![ScreenShot671](https://user-images.githubusercontent.com/17309924/69906725-2302e280-13c8-11ea-9fc8-f1b082d4a821.jpg)

Any ideas why when KeePassium accesses Locations OneDrive share is hidden?
I checked on both my Apple devices - both running iOS 13 - same problem.
Specific versions: OneDrive - _11.10.04_, iPadOS _13.1.3_, KeePassium - _v1.08.48._

**Comment by cappert** [comment]
click the **(...)** button in the top-right corner and add it, it's hidden from me too.

![choose explored clouds](https://user-images.githubusercontent.com/71031/69906821-ca344980-13c9-11ea-8bc9-36364079b64c.png)

**Comment by 0anton** [comment]
OneDrive is not in the list unfortunately:
<img width="317" alt="PNG image" src="https://user-images.githubusercontent.com/17309924/69911741-288c1700-1420-11ea-8c2a-cdcb541cc8fd.png">

OneDrive is only missing when I try to access it from KeePassium. If I for example save a screenshot, I can use OneDrive as a location.

**Comment by keepassium** [comment]
@0anton, most likely this is caused by your company's IT policy regarding OneDrive. Administrators can enforce [quite a few restrictions](https://osddeployment.dk/2017/08/19/manage-intune-mam-from-onedrive-admin-portal-as-sharepoint-admin/) on OneDrive for Business (and the personal OneDrive, too, I guess).

There was another [odd OneDrive issue](https://www.reddit.com/r/KeePassium/comments/keepassium_cant_seem_to_open_keepass_243_kdbx/) that was explained by the Microsoft Intune policy.

P.S. Also, KeePassium has only very little control over the file picker dialog. Basically, it can only specify the types of files it wants...

**Comment by 0anton** [comment]
Hi Andrei, this can be the case (company policy on OneDrive Personal, which restrict usage over 3d applications). With that this is not the issue the KeePassium can solve.
As a workaround, which I found works for me and can be helpful for others, you can do the following trick: connect OneDrive other third party file manager, e.g. FileBrowser app. Then you can locate desired OneDrive folder in KeePassium inside FileBrowser location.

FileBrowser uses the OneDrive API to access the file. Everytime KeePassium opens the database, it fetches the fresh file. So, syncing by writing and refreshing works well.

Since OneDrive access happens directly over networking API, application policies do not apply.

**Comment by keepassium** [comment]
That's a neat trick :) I've added it to [KeePassium's OneDrive FAQ page](https://keepassium.com/articles/sync-ios-keepass-with-onedrive/), to make it more visible for the others.

Thank you for sharing, Anton!

**Comment by kinanzeidan** [comment]
Hi, I am working in a company and we want to use OneDrive to open our keepass files in Keepassium. My company is restricted by the Microsoft SDK, so I asked them to whitelist Keepassium to try it. The problem is that in a company where the security has to be important, we can not use apps which don't follow the SDK restrictions and  where we haven't any control on them.

Is it possible to add the SDK polities to Keepassium ?  
if yes, Did you plan to add SDK polities to Keepassium ?   

Thank you

**Comment by keepassium** [comment]
Hi @kinanzeidan! Yes, this is possible and yes, I plan to do that in the next couple of months. But MS Intune SDK is too heavy and privacy-invasive for the public app, so please send me an email to info@keepassium.com and I will let you know once the business edition is ready. Thanks!
