### ISSUE TITLE
Changing group icon from custom to a default one does not work

### ISSUE THREAD

**Issue by igorkulman** [keepassium/KeePassium#84]
**Describe the bug**
If you have a group with a custom icon set by KeePassXC on macOS the icon shows fine in KeePassium but you cannot change it to any default icon.

**To Reproduce**
1. Use KeePassXC to change icon if a group to a custom icon
2. Edit the group in KeePassium and change the icon to any default icon
3. Observe the icon still showing as the custom icon set by KeePassXC

**Expected behavior**
The icon should be change to the icon set by KeePassium.

**User Information (please complete the following information):**
 - Device: iPhone 11
 - OS: iOS 11.3
 - App Version: 1.08

**Additional context**
If you edit the group again, the default icon you set in step 2 is selected, like KeePassium thinks it is set.

**Comment by keepassium** [comment]
Thanks, Igor. Yeah, this is a side effect of the missing custom icon picker... 

The standard and custom icons are stored as two independent properties of the group. When both are defined, the app draws the custom icon. KeePassium's icon picker changes the standard icon, but does not work with custom icons yet. (The custom icon picker has a low priority, because nobody ever asked for it so far...)
