### ISSUE TITLE
Option to show password when viewing entry

### ISSUE THREAD

**Issue by jborlik** [keepassium/KeePassium#95]
When viewing an entry, typically one wants to view the password.  It requires a second finger press (on the little eye icon) to show the password.  It would be nice to have the option to always immediately show the password (without the extra user interaction).

(MiniKeePass behaved that way, and it seemed to make my interaction with it quicker.  And I recognize that it is a small thing, but given that I look at this app many many times a day, little things like this add up.)

**Comment by keepassium** [comment]
Thank you for the suggestion!

> When viewing an entry, typically one wants to view the password.

For me, it is almost alway to copy the password rather than view it. But this is clearly a matter of personal use cases... 

I don't mind to make passwords visible (optionally), but maybe there is a better solution for your usage scenario.

Can you please describe a bit why you want to view the passwords?

- To type it into a computer? Your own computer or somebody else's? 
- To show it to someone? (family, colleague, etc)
- To find and enter a few characters? (some banks require the "3rd, 5th and 9th symbol of your password")
- Something else?

Thanks!

**Comment by jborlik** [comment]
Thanks for the response, and thoughtful question.  You are absolutely correct that, on the iOS device itself, viewing the password isn't necessary.  

The use-case I am thinking of it to "type it into another computer".  I typically use my phone as the way to access the passwords, for my other devices.  Especially at work, I have a couple of machines where I need to access my passwords, and it just seems easier to have one interface to get at them.  

I recognize that I could use the full KeePass application, for some of those machines, along with a cloud-based syncing of the databases.  Perhaps I'm used to MiniKeePass, which required manual steps to sync.  But, some other computers, in particular work ones, do not have access to cloud storage.

**Comment by keepassium** [comment]
Thank you for the details!

I have implemented the setting in the dev version. 

By the way, there are alternatives to manual typing:

- For your Apple devices, there is [Universal Clipboard](https://support.apple.com/en-us/HT209460). Currently it is disabled in KeePassium, but will become an option in the next update.
- For Windows/Linux machines, there is [InputStick](http://inputstick.com) which emulates a USB keyboard controlled from the phone.
